version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"
    open-pull-requests-limit: 10
    groups:
      maven-version-updates:
        patterns:
          - "*"
        applies-to: "version-updates"
      maven-security-updates:
        patterns:
          - "*"
        applies-to: "security-updates"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"
    open-pull-requests-limit: 10
    groups:
      actions-version-updates:
        patterns:
          - "*"
        applies-to: "version-updates"
      actions-security-updates:
        patterns:
          - "*"
        applies-to: "security-updates"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
