version: 2
updates:
    - package-ecosystem: "maven"
      schedule:
          interval: "weekly"
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
