/*
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zitadel.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zitadel.model.ActionServicePaginationResponse;
import com.zitadel.model.ActionServicePublicKey;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * ActionServiceListPublicKeysResponse
 */
@JsonPropertyOrder({
  ActionServiceListPublicKeysResponse.JSON_PROPERTY_PAGINATION,
  ActionServiceListPublicKeysResponse.JSON_PROPERTY_PUBLIC_KEYS
})
@javax.annotation.Generated(value = "io.github.mridang.codegen.generators.java.BetterJavaCodegen", comments = "Generator version: 7.14.0")
public class ActionServiceListPublicKeysResponse {
  public static final String JSON_PROPERTY_PAGINATION = "pagination";
  @javax.annotation.Nullable
  private ActionServicePaginationResponse pagination;

  public static final String JSON_PROPERTY_PUBLIC_KEYS = "publicKeys";
  @javax.annotation.Nullable
  private List<ActionServicePublicKey> publicKeys = new ArrayList<>();

  public ActionServiceListPublicKeysResponse() {
  }

  public ActionServiceListPublicKeysResponse pagination(@javax.annotation.Nullable ActionServicePaginationResponse pagination) {
    
    this.pagination = pagination;
    return this;
  }

  /**
   * Get pagination
   * @return pagination
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAGINATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ActionServicePaginationResponse getPagination() {
    return pagination;
  }


  @JsonProperty(JSON_PROPERTY_PAGINATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPagination(@javax.annotation.Nullable ActionServicePaginationResponse pagination) {
    this.pagination = pagination;
  }

  public ActionServiceListPublicKeysResponse publicKeys(@javax.annotation.Nullable List<ActionServicePublicKey> publicKeys) {
    
    this.publicKeys = publicKeys;
    return this;
  }

  public ActionServiceListPublicKeysResponse addPublicKeysItem(ActionServicePublicKey publicKeysItem) {
    if (this.publicKeys == null) {
      this.publicKeys = new ArrayList<>();
    }
    this.publicKeys.add(publicKeysItem);
    return this;
  }

  /**
   * List of all public keys for the target.
   * @return publicKeys
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUBLIC_KEYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ActionServicePublicKey> getPublicKeys() {
    return publicKeys;
  }


  @JsonProperty(JSON_PROPERTY_PUBLIC_KEYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPublicKeys(@javax.annotation.Nullable List<ActionServicePublicKey> publicKeys) {
    this.publicKeys = publicKeys;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActionServiceListPublicKeysResponse actionServiceListPublicKeysResponse = (ActionServiceListPublicKeysResponse) o;
    return Objects.equals(this.pagination, actionServiceListPublicKeysResponse.pagination) &&
        Objects.equals(this.publicKeys, actionServiceListPublicKeysResponse.publicKeys);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pagination, publicKeys);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActionServiceListPublicKeysResponse {\n");
    sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
    sb.append("    publicKeys: ").append(toIndentedString(publicKeys)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `pagination` to the URL query string
    if (getPagination() != null) {
      joiner.add(getPagination().toUrlQueryString(prefix + "pagination" + suffix));
    }

    // add `publicKeys` to the URL query string
    if (getPublicKeys() != null) {
      for (int i = 0; i < getPublicKeys().size(); i++) {
        if (getPublicKeys().get(i) != null) {
          joiner.add(getPublicKeys().get(i).toUrlQueryString(String.format("%spublicKeys%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }

}

