/*
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zitadel.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zitadel.model.ActionServiceBetaRESTCall;
import com.zitadel.model.ActionServiceBetaRESTWebhook;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * ActionServiceBetaTarget
 */
@JsonPropertyOrder({
  ActionServiceBetaTarget.JSON_PROPERTY_ID,
  ActionServiceBetaTarget.JSON_PROPERTY_CREATION_DATE,
  ActionServiceBetaTarget.JSON_PROPERTY_CHANGE_DATE,
  ActionServiceBetaTarget.JSON_PROPERTY_NAME,
  ActionServiceBetaTarget.JSON_PROPERTY_REST_WEBHOOK,
  ActionServiceBetaTarget.JSON_PROPERTY_REST_CALL,
  ActionServiceBetaTarget.JSON_PROPERTY_REST_ASYNC,
  ActionServiceBetaTarget.JSON_PROPERTY_TIMEOUT,
  ActionServiceBetaTarget.JSON_PROPERTY_ENDPOINT,
  ActionServiceBetaTarget.JSON_PROPERTY_SIGNING_KEY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class ActionServiceBetaTarget {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_CREATION_DATE = "creationDate";
  @javax.annotation.Nullable
  private OffsetDateTime creationDate;

  public static final String JSON_PROPERTY_CHANGE_DATE = "changeDate";
  @javax.annotation.Nullable
  private OffsetDateTime changeDate;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_REST_WEBHOOK = "restWebhook";
  @javax.annotation.Nullable
  private ActionServiceBetaRESTWebhook restWebhook;

  public static final String JSON_PROPERTY_REST_CALL = "restCall";
  @javax.annotation.Nullable
  private ActionServiceBetaRESTCall restCall;

  public static final String JSON_PROPERTY_REST_ASYNC = "restAsync";
  @javax.annotation.Nullable
  private Object restAsync;

  public static final String JSON_PROPERTY_TIMEOUT = "timeout";
  @javax.annotation.Nullable
  private String timeout;

  public static final String JSON_PROPERTY_ENDPOINT = "endpoint";
  @javax.annotation.Nullable
  private String endpoint;

  public static final String JSON_PROPERTY_SIGNING_KEY = "signingKey";
  @javax.annotation.Nullable
  private String signingKey;

  public ActionServiceBetaTarget() {
  }

  public ActionServiceBetaTarget id(@javax.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * The unique identifier of the target.
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }

  public ActionServiceBetaTarget creationDate(@javax.annotation.Nullable OffsetDateTime creationDate) {
    
    this.creationDate = creationDate;
    return this;
  }

  /**
   * The timestamp of the target creation.
   * @return creationDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreationDate() {
    return creationDate;
  }


  @JsonProperty(JSON_PROPERTY_CREATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreationDate(@javax.annotation.Nullable OffsetDateTime creationDate) {
    this.creationDate = creationDate;
  }

  public ActionServiceBetaTarget changeDate(@javax.annotation.Nullable OffsetDateTime changeDate) {
    
    this.changeDate = changeDate;
    return this;
  }

  /**
   * The timestamp of the last change to the target (e.g. creation, activation, deactivation).
   * @return changeDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHANGE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getChangeDate() {
    return changeDate;
  }


  @JsonProperty(JSON_PROPERTY_CHANGE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChangeDate(@javax.annotation.Nullable OffsetDateTime changeDate) {
    this.changeDate = changeDate;
  }

  public ActionServiceBetaTarget name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public ActionServiceBetaTarget restWebhook(@javax.annotation.Nullable ActionServiceBetaRESTWebhook restWebhook) {
    
    this.restWebhook = restWebhook;
    return this;
  }

  /**
   * Get restWebhook
   * @return restWebhook
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REST_WEBHOOK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ActionServiceBetaRESTWebhook getRestWebhook() {
    return restWebhook;
  }


  @JsonProperty(JSON_PROPERTY_REST_WEBHOOK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRestWebhook(@javax.annotation.Nullable ActionServiceBetaRESTWebhook restWebhook) {
    this.restWebhook = restWebhook;
  }

  public ActionServiceBetaTarget restCall(@javax.annotation.Nullable ActionServiceBetaRESTCall restCall) {
    
    this.restCall = restCall;
    return this;
  }

  /**
   * Get restCall
   * @return restCall
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REST_CALL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ActionServiceBetaRESTCall getRestCall() {
    return restCall;
  }


  @JsonProperty(JSON_PROPERTY_REST_CALL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRestCall(@javax.annotation.Nullable ActionServiceBetaRESTCall restCall) {
    this.restCall = restCall;
  }

  public ActionServiceBetaTarget restAsync(@javax.annotation.Nullable Object restAsync) {
    
    this.restAsync = restAsync;
    return this;
  }

  /**
   * Get restAsync
   * @return restAsync
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REST_ASYNC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getRestAsync() {
    return restAsync;
  }


  @JsonProperty(JSON_PROPERTY_REST_ASYNC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRestAsync(@javax.annotation.Nullable Object restAsync) {
    this.restAsync = restAsync;
  }

  public ActionServiceBetaTarget timeout(@javax.annotation.Nullable String timeout) {
    
    this.timeout = timeout;
    return this;
  }

  /**
   * Timeout defines the duration until ZITADEL cancels the execution. If the target doesn&#39;t respond before this timeout expires, the the connection is closed and the action fails. Depending on the target type and possible setting on &#x60;interrupt_on_error&#x60; following targets will not be called. In case of a &#x60;rest_async&#x60; target only this specific target will fail, without any influence on other targets of the same execution.
   * @return timeout
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIMEOUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimeout() {
    return timeout;
  }


  @JsonProperty(JSON_PROPERTY_TIMEOUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeout(@javax.annotation.Nullable String timeout) {
    this.timeout = timeout;
  }

  public ActionServiceBetaTarget endpoint(@javax.annotation.Nullable String endpoint) {
    
    this.endpoint = endpoint;
    return this;
  }

  /**
   * Get endpoint
   * @return endpoint
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENDPOINT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEndpoint() {
    return endpoint;
  }


  @JsonProperty(JSON_PROPERTY_ENDPOINT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndpoint(@javax.annotation.Nullable String endpoint) {
    this.endpoint = endpoint;
  }

  public ActionServiceBetaTarget signingKey(@javax.annotation.Nullable String signingKey) {
    
    this.signingKey = signingKey;
    return this;
  }

  /**
   * Get signingKey
   * @return signingKey
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGNING_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSigningKey() {
    return signingKey;
  }


  @JsonProperty(JSON_PROPERTY_SIGNING_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSigningKey(@javax.annotation.Nullable String signingKey) {
    this.signingKey = signingKey;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActionServiceBetaTarget actionServiceBetaTarget = (ActionServiceBetaTarget) o;
    return Objects.equals(this.id, actionServiceBetaTarget.id) &&
        Objects.equals(this.creationDate, actionServiceBetaTarget.creationDate) &&
        Objects.equals(this.changeDate, actionServiceBetaTarget.changeDate) &&
        Objects.equals(this.name, actionServiceBetaTarget.name) &&
        Objects.equals(this.restWebhook, actionServiceBetaTarget.restWebhook) &&
        Objects.equals(this.restCall, actionServiceBetaTarget.restCall) &&
        Objects.equals(this.restAsync, actionServiceBetaTarget.restAsync) &&
        Objects.equals(this.timeout, actionServiceBetaTarget.timeout) &&
        Objects.equals(this.endpoint, actionServiceBetaTarget.endpoint) &&
        Objects.equals(this.signingKey, actionServiceBetaTarget.signingKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, creationDate, changeDate, name, restWebhook, restCall, restAsync, timeout, endpoint, signingKey);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActionServiceBetaTarget {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    changeDate: ").append(toIndentedString(changeDate)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    restWebhook: ").append(toIndentedString(restWebhook)).append("\n");
    sb.append("    restCall: ").append(toIndentedString(restCall)).append("\n");
    sb.append("    restAsync: ").append(toIndentedString(restAsync)).append("\n");
    sb.append("    timeout: ").append(toIndentedString(timeout)).append("\n");
    sb.append("    endpoint: ").append(toIndentedString(endpoint)).append("\n");
    sb.append("    signingKey: ").append(toIndentedString(signingKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    return joiner.toString();
  }

}

