// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating
// with your Zitadel environment. This SDK enables you to handle resources, settings, and
// configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

package com.zitadel.model;

/** BetaUserServiceUserFieldName. */
@SuppressWarnings({
  "checkstyle:SummaryJavadoc",
  "checkstyle:JavadocParagraph",
  "checkstyle:SingleLineJavadoc",
  "checkstyle:RequireEmptyLineBeforeBlockTagGroup",
  "checkstyle:NonEmptyAtclauseDescription",
  "checkstyle:JavadocTagContinuationIndentation",
  "checkstyle:AtclauseOrder",
  "checkstyle:InvalidJavadocPosition",
  "checkstyle:AbbreviationAsWordInName",
  "checkstyle:MemberName",
  "checkstyle:OverloadMethodsDeclarationOrder",
  "checkstyle:VariableDeclarationUsageDistance",
  "checkstyle:ConstructorsDeclarationGrouping"
})
public enum BetaUserServiceUserFieldName {
  /** The {@code "USER_FIELD_NAME_UNSPECIFIED"} value. */
  USER_FIELD_NAME_UNSPECIFIED("USER_FIELD_NAME_UNSPECIFIED"),
  /** The {@code "USER_FIELD_NAME_USER_NAME"} value. */
  USER_FIELD_NAME_USER_NAME("USER_FIELD_NAME_USER_NAME"),
  /** The {@code "USER_FIELD_NAME_FIRST_NAME"} value. */
  USER_FIELD_NAME_FIRST_NAME("USER_FIELD_NAME_FIRST_NAME"),
  /** The {@code "USER_FIELD_NAME_LAST_NAME"} value. */
  USER_FIELD_NAME_LAST_NAME("USER_FIELD_NAME_LAST_NAME"),
  /** The {@code "USER_FIELD_NAME_NICK_NAME"} value. */
  USER_FIELD_NAME_NICK_NAME("USER_FIELD_NAME_NICK_NAME"),
  /** The {@code "USER_FIELD_NAME_DISPLAY_NAME"} value. */
  USER_FIELD_NAME_DISPLAY_NAME("USER_FIELD_NAME_DISPLAY_NAME"),
  /** The {@code "USER_FIELD_NAME_EMAIL"} value. */
  USER_FIELD_NAME_EMAIL("USER_FIELD_NAME_EMAIL"),
  /** The {@code "USER_FIELD_NAME_STATE"} value. */
  USER_FIELD_NAME_STATE("USER_FIELD_NAME_STATE"),
  /** The {@code "USER_FIELD_NAME_TYPE"} value. */
  USER_FIELD_NAME_TYPE("USER_FIELD_NAME_TYPE"),
  /** The {@code "USER_FIELD_NAME_CREATION_DATE"} value. */
  USER_FIELD_NAME_CREATION_DATE("USER_FIELD_NAME_CREATION_DATE");

  private final String value;

  BetaUserServiceUserFieldName(String value) {
    this.value = value;
  }

  /**
   * Returns the wire value of this enum constant.
   *
   * @return the wire value
   */
  @com.fasterxml.jackson.annotation.JsonValue
  public String getValue() {
    return value;
  }

  /**
   * Returns the enum constant for the given wire value.
   *
   * @param value the wire value
   * @return the matching enum constant
   * @throws IllegalArgumentException if no constant matches
   */
  @com.fasterxml.jackson.annotation.JsonCreator
  public static BetaUserServiceUserFieldName fromValue(String value) {
    for (BetaUserServiceUserFieldName b : values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
