// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating
// with your Zitadel environment. This SDK enables you to handle resources, settings, and
// configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

package com.zitadel.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import javax.annotation.Nullable;

/** BetaAppServiceApplicationSearchFilter. */
public class BetaAppServiceApplicationSearchFilter {

  /** The {@code apiAppOnly} property. */
  @JsonProperty("apiAppOnly")
  @Nullable
  public Boolean apiAppOnly;

  /** The {@code nameFilter} property. */
  @JsonProperty("nameFilter")
  @Nullable
  public BetaAppServiceApplicationNameQuery nameFilter;

  /** The {@code oidcAppOnly} property. */
  @JsonProperty("oidcAppOnly")
  @Nullable
  public Boolean oidcAppOnly;

  /** The {@code samlAppOnly} property. */
  @JsonProperty("samlAppOnly")
  @Nullable
  public Boolean samlAppOnly;

  /** The {@code stateFilter} property. */
  @JsonProperty("stateFilter")
  @Nullable
  public BetaAppServiceAppState stateFilter;

  /** Creates an empty instance. */
  public BetaAppServiceApplicationSearchFilter() {}

  /* Value-equality based on all declared fields. Generated so model
   * instances work correctly as Set/Map keys and in test assertions.
   * Uses pattern-matching `instanceof other` (Java 16+) — required by
   * Error Prone's PatternMatchingInstanceof rule and avoids the
   * EqualsGetClass warning that plain getClass() comparison triggers. */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof BetaAppServiceApplicationSearchFilter other)) {
      return false;
    }
    return java.util.Objects.equals(this.apiAppOnly, other.apiAppOnly)
        && java.util.Objects.equals(this.nameFilter, other.nameFilter)
        && java.util.Objects.equals(this.oidcAppOnly, other.oidcAppOnly)
        && java.util.Objects.equals(this.samlAppOnly, other.samlAppOnly)
        && java.util.Objects.equals(this.stateFilter, other.stateFilter);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(apiAppOnly, nameFilter, oidcAppOnly, samlAppOnly, stateFilter);
  }
}
