/*
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zitadel.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zitadel.model.BetaInternalPermissionServiceAdministrator;
import com.zitadel.model.BetaInternalPermissionServicePaginationResponse;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * BetaInternalPermissionServiceListAdministratorsResponse
 */
@JsonPropertyOrder({
  BetaInternalPermissionServiceListAdministratorsResponse.JSON_PROPERTY_PAGINATION,
  BetaInternalPermissionServiceListAdministratorsResponse.JSON_PROPERTY_ADMINISTRATORS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class BetaInternalPermissionServiceListAdministratorsResponse {
  public static final String JSON_PROPERTY_PAGINATION = "pagination";
  @javax.annotation.Nullable
  private BetaInternalPermissionServicePaginationResponse pagination;

  public static final String JSON_PROPERTY_ADMINISTRATORS = "administrators";
  @javax.annotation.Nullable
  private List<BetaInternalPermissionServiceAdministrator> administrators = new ArrayList<>();

  public BetaInternalPermissionServiceListAdministratorsResponse() {
  }

  public BetaInternalPermissionServiceListAdministratorsResponse pagination(@javax.annotation.Nullable BetaInternalPermissionServicePaginationResponse pagination) {
    
    this.pagination = pagination;
    return this;
  }

  /**
   * Get pagination
   * @return pagination
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAGINATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BetaInternalPermissionServicePaginationResponse getPagination() {
    return pagination;
  }


  @JsonProperty(JSON_PROPERTY_PAGINATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPagination(@javax.annotation.Nullable BetaInternalPermissionServicePaginationResponse pagination) {
    this.pagination = pagination;
  }

  public BetaInternalPermissionServiceListAdministratorsResponse administrators(@javax.annotation.Nullable List<BetaInternalPermissionServiceAdministrator> administrators) {
    
    this.administrators = administrators;
    return this;
  }

  public BetaInternalPermissionServiceListAdministratorsResponse addAdministratorsItem(BetaInternalPermissionServiceAdministrator administratorsItem) {
    if (this.administrators == null) {
      this.administrators = new ArrayList<>();
    }
    this.administrators.add(administratorsItem);
    return this;
  }

  /**
   * Get administrators
   * @return administrators
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADMINISTRATORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<BetaInternalPermissionServiceAdministrator> getAdministrators() {
    return administrators;
  }


  @JsonProperty(JSON_PROPERTY_ADMINISTRATORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdministrators(@javax.annotation.Nullable List<BetaInternalPermissionServiceAdministrator> administrators) {
    this.administrators = administrators;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BetaInternalPermissionServiceListAdministratorsResponse betaInternalPermissionServiceListAdministratorsResponse = (BetaInternalPermissionServiceListAdministratorsResponse) o;
    return Objects.equals(this.pagination, betaInternalPermissionServiceListAdministratorsResponse.pagination) &&
        Objects.equals(this.administrators, betaInternalPermissionServiceListAdministratorsResponse.administrators);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pagination, administrators);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BetaInternalPermissionServiceListAdministratorsResponse {\n");
    sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
    sb.append("    administrators: ").append(toIndentedString(administrators)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `pagination` to the URL query string
    if (getPagination() != null) {
      joiner.add(getPagination().toUrlQueryString(prefix + "pagination" + suffix));
    }

    // add `administrators` to the URL query string
    if (getAdministrators() != null) {
      for (int i = 0; i < getAdministrators().size(); i++) {
        if (getAdministrators().get(i) != null) {
          joiner.add(getAdministrators().get(i).toUrlQueryString(String.format("%sadministrators%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }

}

