/*
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zitadel.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets BetaAppServiceOIDCAuthMethodType
 */
public enum BetaAppServiceOIDCAuthMethodType {

  OIDC_AUTH_METHOD_TYPE_BASIC("OIDC_AUTH_METHOD_TYPE_BASIC"),

  OIDC_AUTH_METHOD_TYPE_POST("OIDC_AUTH_METHOD_TYPE_POST"),

  OIDC_AUTH_METHOD_TYPE_NONE("OIDC_AUTH_METHOD_TYPE_NONE"),

  OIDC_AUTH_METHOD_TYPE_PRIVATE_KEY_JWT("OIDC_AUTH_METHOD_TYPE_PRIVATE_KEY_JWT");

  private String value;

  BetaAppServiceOIDCAuthMethodType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static BetaAppServiceOIDCAuthMethodType fromValue(String value) {
    for (BetaAppServiceOIDCAuthMethodType b : BetaAppServiceOIDCAuthMethodType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    if (prefix == null) {
      prefix = "";
    }

    return String.format("%s=%s", prefix, this.toString());
  }
}
