/*
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zitadel.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * BetaAuthorizationServiceUserPreferredLoginNameQuery
 */
@JsonPropertyOrder({
  BetaAuthorizationServiceUserPreferredLoginNameQuery.JSON_PROPERTY_LOGIN_NAME,
  BetaAuthorizationServiceUserPreferredLoginNameQuery.JSON_PROPERTY_METHOD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class BetaAuthorizationServiceUserPreferredLoginNameQuery {
  public static final String JSON_PROPERTY_LOGIN_NAME = "loginName";
  @javax.annotation.Nullable
  private String loginName;

  public static final String JSON_PROPERTY_METHOD = "method";
  @javax.annotation.Nullable
  private BetaAuthorizationServiceTextFilterMethod method;

  public BetaAuthorizationServiceUserPreferredLoginNameQuery() {
  }

  public BetaAuthorizationServiceUserPreferredLoginNameQuery loginName(@javax.annotation.Nullable String loginName) {

    this.loginName = loginName;
    return this;
  }

  /**
   * Specify the preferred login name of the granted user to search for.
   * @return loginName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOGIN_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLoginName() {
    return loginName;
  }


  @JsonProperty(JSON_PROPERTY_LOGIN_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoginName(@javax.annotation.Nullable String loginName) {
    this.loginName = loginName;
  }

  public BetaAuthorizationServiceUserPreferredLoginNameQuery method(@javax.annotation.Nullable BetaAuthorizationServiceTextFilterMethod method) {

    this.method = method;
    return this;
  }

  /**
   * Get method
   * @return method
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BetaAuthorizationServiceTextFilterMethod getMethod() {
    return method;
  }


  @JsonProperty(JSON_PROPERTY_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMethod(@javax.annotation.Nullable BetaAuthorizationServiceTextFilterMethod method) {
    this.method = method;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BetaAuthorizationServiceUserPreferredLoginNameQuery betaAuthorizationServiceUserPreferredLoginNameQuery = (BetaAuthorizationServiceUserPreferredLoginNameQuery) o;
    return Objects.equals(this.loginName, betaAuthorizationServiceUserPreferredLoginNameQuery.loginName) &&
        Objects.equals(this.method, betaAuthorizationServiceUserPreferredLoginNameQuery.method);
  }

  @Override
  public int hashCode() {
    return Objects.hash(loginName, method);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BetaAuthorizationServiceUserPreferredLoginNameQuery {\n");
    sb.append("    loginName: ").append(toIndentedString(loginName)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `loginName` to the URL query string
    if (getLoginName() != null) {
      try {
        joiner.add(String.format("%sloginName%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLoginName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `method` to the URL query string
    if (getMethod() != null) {
      try {
        joiner.add(String.format("%smethod%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMethod()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}
