/*
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zitadel.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zitadel.model.BetaUserServiceListQuery;
import com.zitadel.model.BetaUserServiceSearchQuery;
import com.zitadel.model.BetaUserServiceUserFieldName;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * BetaUserServiceListUsersRequest
 */
@JsonPropertyOrder({
  BetaUserServiceListUsersRequest.JSON_PROPERTY_QUERY,
  BetaUserServiceListUsersRequest.JSON_PROPERTY_SORTING_COLUMN,
  BetaUserServiceListUsersRequest.JSON_PROPERTY_QUERIES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class BetaUserServiceListUsersRequest {
  public static final String JSON_PROPERTY_QUERY = "query";
  @javax.annotation.Nullable
  private BetaUserServiceListQuery query;

  public static final String JSON_PROPERTY_SORTING_COLUMN = "sortingColumn";
  @javax.annotation.Nullable
  private BetaUserServiceUserFieldName sortingColumn;

  public static final String JSON_PROPERTY_QUERIES = "queries";
  @javax.annotation.Nullable
  private List<BetaUserServiceSearchQuery> queries = new ArrayList<>();

  public BetaUserServiceListUsersRequest() {
  }

  public BetaUserServiceListUsersRequest query(@javax.annotation.Nullable BetaUserServiceListQuery query) {
    
    this.query = query;
    return this;
  }

  /**
   * Get query
   * @return query
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BetaUserServiceListQuery getQuery() {
    return query;
  }


  @JsonProperty(JSON_PROPERTY_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuery(@javax.annotation.Nullable BetaUserServiceListQuery query) {
    this.query = query;
  }

  public BetaUserServiceListUsersRequest sortingColumn(@javax.annotation.Nullable BetaUserServiceUserFieldName sortingColumn) {
    
    this.sortingColumn = sortingColumn;
    return this;
  }

  /**
   * Get sortingColumn
   * @return sortingColumn
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SORTING_COLUMN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BetaUserServiceUserFieldName getSortingColumn() {
    return sortingColumn;
  }


  @JsonProperty(JSON_PROPERTY_SORTING_COLUMN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSortingColumn(@javax.annotation.Nullable BetaUserServiceUserFieldName sortingColumn) {
    this.sortingColumn = sortingColumn;
  }

  public BetaUserServiceListUsersRequest queries(@javax.annotation.Nullable List<BetaUserServiceSearchQuery> queries) {
    
    this.queries = queries;
    return this;
  }

  public BetaUserServiceListUsersRequest addQueriesItem(BetaUserServiceSearchQuery queriesItem) {
    if (this.queries == null) {
      this.queries = new ArrayList<>();
    }
    this.queries.add(queriesItem);
    return this;
  }

  /**
   * criteria the client is looking for
   * @return queries
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUERIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<BetaUserServiceSearchQuery> getQueries() {
    return queries;
  }


  @JsonProperty(JSON_PROPERTY_QUERIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQueries(@javax.annotation.Nullable List<BetaUserServiceSearchQuery> queries) {
    this.queries = queries;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BetaUserServiceListUsersRequest betaUserServiceListUsersRequest = (BetaUserServiceListUsersRequest) o;
    return Objects.equals(this.query, betaUserServiceListUsersRequest.query) &&
        Objects.equals(this.sortingColumn, betaUserServiceListUsersRequest.sortingColumn) &&
        Objects.equals(this.queries, betaUserServiceListUsersRequest.queries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(query, sortingColumn, queries);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BetaUserServiceListUsersRequest {\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    sortingColumn: ").append(toIndentedString(sortingColumn)).append("\n");
    sb.append("    queries: ").append(toIndentedString(queries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `query` to the URL query string
    if (getQuery() != null) {
      joiner.add(getQuery().toUrlQueryString(prefix + "query" + suffix));
    }

    // add `sortingColumn` to the URL query string
    if (getSortingColumn() != null) {
      try {
        joiner.add(String.format("%ssortingColumn%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSortingColumn()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `queries` to the URL query string
    if (getQueries() != null) {
      for (int i = 0; i < getQueries().size(); i++) {
        if (getQueries().get(i) != null) {
          joiner.add(getQueries().get(i).toUrlQueryString(String.format("%squeries%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }

}

