// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating
// with your Zitadel environment. This SDK enables you to handle resources, settings, and
// configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

package com.zitadel.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import javax.annotation.Nullable;

/** BetaInternalPermissionServiceOrganization. */
@SuppressWarnings({
  "checkstyle:SummaryJavadoc",
  "checkstyle:JavadocParagraph",
  "checkstyle:SingleLineJavadoc",
  "checkstyle:RequireEmptyLineBeforeBlockTagGroup",
  "checkstyle:NonEmptyAtclauseDescription",
  "checkstyle:JavadocTagContinuationIndentation",
  "checkstyle:AtclauseOrder",
  "checkstyle:InvalidJavadocPosition",
  "checkstyle:AbbreviationAsWordInName",
  "checkstyle:MemberName",
  "checkstyle:OverloadMethodsDeclarationOrder",
  "checkstyle:VariableDeclarationUsageDistance",
  "checkstyle:ConstructorsDeclarationGrouping"
})
public class BetaInternalPermissionServiceOrganization {

  /**
   * ID is the unique identifier of the organization the user was granted the administrator role
   * for.
   *
   * <p>Example: {@code null}
   */
  @JsonProperty("id")
  @Nullable
  public String id;

  /**
   * Name is the name of the organization the user was granted the administrator role for.
   *
   * <p>Example: {@code null}
   */
  @JsonProperty("name")
  @Nullable
  public String name;

  /** Creates an empty instance. */
  public BetaInternalPermissionServiceOrganization() {}

  /* Value-equality based on all declared fields. Generated so model
   * instances work correctly as Set/Map keys and in test assertions.
   * Uses pattern-matching `instanceof other` (Java 16+) — required by
   * Error Prone's PatternMatchingInstanceof rule and avoids the
   * EqualsGetClass warning that plain getClass() comparison triggers. */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof BetaInternalPermissionServiceOrganization other)) {
      return false;
    }
    return java.util.Objects.equals(this.id, other.id)
        && java.util.Objects.equals(this.name, other.name);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, name);
  }
}
