/*
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zitadel.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zitadel.model.BetaUserServiceDetails;
import com.zitadel.model.BetaUserServiceValue;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * BetaUserServiceRegisterU2FResponse
 */
@JsonPropertyOrder({
  BetaUserServiceRegisterU2FResponse.JSON_PROPERTY_DETAILS,
  BetaUserServiceRegisterU2FResponse.JSON_PROPERTY_U2F_ID,
  BetaUserServiceRegisterU2FResponse.JSON_PROPERTY_PUBLIC_KEY_CREDENTIAL_CREATION_OPTIONS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class BetaUserServiceRegisterU2FResponse {
  public static final String JSON_PROPERTY_DETAILS = "details";
  @javax.annotation.Nullable
  private BetaUserServiceDetails details;

  public static final String JSON_PROPERTY_U2F_ID = "u2fId";
  @javax.annotation.Nullable
  private String u2fId;

  public static final String JSON_PROPERTY_PUBLIC_KEY_CREDENTIAL_CREATION_OPTIONS = "publicKeyCredentialCreationOptions";
  @javax.annotation.Nullable
  private Map<String, BetaUserServiceValue> publicKeyCredentialCreationOptions = new HashMap<>();

  public BetaUserServiceRegisterU2FResponse() {
  }

  public BetaUserServiceRegisterU2FResponse details(@javax.annotation.Nullable BetaUserServiceDetails details) {
    
    this.details = details;
    return this;
  }

  /**
   * Get details
   * @return details
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BetaUserServiceDetails getDetails() {
    return details;
  }


  @JsonProperty(JSON_PROPERTY_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDetails(@javax.annotation.Nullable BetaUserServiceDetails details) {
    this.details = details;
  }

  public BetaUserServiceRegisterU2FResponse u2fId(@javax.annotation.Nullable String u2fId) {
    
    this.u2fId = u2fId;
    return this;
  }

  /**
   * Get u2fId
   * @return u2fId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_U2F_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getU2fId() {
    return u2fId;
  }


  @JsonProperty(JSON_PROPERTY_U2F_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setU2fId(@javax.annotation.Nullable String u2fId) {
    this.u2fId = u2fId;
  }

  public BetaUserServiceRegisterU2FResponse publicKeyCredentialCreationOptions(@javax.annotation.Nullable Map<String, BetaUserServiceValue> publicKeyCredentialCreationOptions) {
    
    this.publicKeyCredentialCreationOptions = publicKeyCredentialCreationOptions;
    return this;
  }

  public BetaUserServiceRegisterU2FResponse putPublicKeyCredentialCreationOptionsItem(String key, BetaUserServiceValue publicKeyCredentialCreationOptionsItem) {
    if (this.publicKeyCredentialCreationOptions == null) {
      this.publicKeyCredentialCreationOptions = new HashMap<>();
    }
    this.publicKeyCredentialCreationOptions.put(key, publicKeyCredentialCreationOptionsItem);
    return this;
  }

  /**
   * &#x60;Struct&#x60; represents a structured data value, consisting of fields  which map to dynamically typed values. In some languages, &#x60;Struct&#x60;  might be supported by a native representation. For example, in  scripting languages like JS a struct is represented as an  object. The details of that representation are described together  with the proto support for the language.   The JSON representation for &#x60;Struct&#x60; is JSON object.
   * @return publicKeyCredentialCreationOptions
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUBLIC_KEY_CREDENTIAL_CREATION_OPTIONS)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, BetaUserServiceValue> getPublicKeyCredentialCreationOptions() {
    return publicKeyCredentialCreationOptions;
  }


  @JsonProperty(JSON_PROPERTY_PUBLIC_KEY_CREDENTIAL_CREATION_OPTIONS)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setPublicKeyCredentialCreationOptions(@javax.annotation.Nullable Map<String, BetaUserServiceValue> publicKeyCredentialCreationOptions) {
    this.publicKeyCredentialCreationOptions = publicKeyCredentialCreationOptions;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BetaUserServiceRegisterU2FResponse betaUserServiceRegisterU2FResponse = (BetaUserServiceRegisterU2FResponse) o;
    return Objects.equals(this.details, betaUserServiceRegisterU2FResponse.details) &&
        Objects.equals(this.u2fId, betaUserServiceRegisterU2FResponse.u2fId) &&
        Objects.equals(this.publicKeyCredentialCreationOptions, betaUserServiceRegisterU2FResponse.publicKeyCredentialCreationOptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(details, u2fId, publicKeyCredentialCreationOptions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BetaUserServiceRegisterU2FResponse {\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    u2fId: ").append(toIndentedString(u2fId)).append("\n");
    sb.append("    publicKeyCredentialCreationOptions: ").append(toIndentedString(publicKeyCredentialCreationOptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `details` to the URL query string
    if (getDetails() != null) {
      joiner.add(getDetails().toUrlQueryString(prefix + "details" + suffix));
    }

    // add `u2fId` to the URL query string
    if (getU2fId() != null) {
      try {
        joiner.add(String.format("%su2fId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getU2fId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `publicKeyCredentialCreationOptions` to the URL query string
    if (getPublicKeyCredentialCreationOptions() != null) {
      for (String _key : getPublicKeyCredentialCreationOptions().keySet()) {
        if (getPublicKeyCredentialCreationOptions().get(_key) != null) {
          joiner.add(getPublicKeyCredentialCreationOptions().get(_key).toUrlQueryString(String.format("%spublicKeyCredentialCreationOptions%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }

}

