/*
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zitadel.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zitadel.model.BetaSessionServiceIntentFactor;
import com.zitadel.model.BetaSessionServiceOTPFactor;
import com.zitadel.model.BetaSessionServicePasswordFactor;
import com.zitadel.model.BetaSessionServiceTOTPFactor;
import com.zitadel.model.BetaSessionServiceUserFactor;
import com.zitadel.model.BetaSessionServiceWebAuthNFactor;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * BetaSessionServiceFactors
 */
@JsonPropertyOrder({
  BetaSessionServiceFactors.JSON_PROPERTY_USER,
  BetaSessionServiceFactors.JSON_PROPERTY_PASSWORD,
  BetaSessionServiceFactors.JSON_PROPERTY_WEB_AUTH_N,
  BetaSessionServiceFactors.JSON_PROPERTY_INTENT,
  BetaSessionServiceFactors.JSON_PROPERTY_TOTP,
  BetaSessionServiceFactors.JSON_PROPERTY_OTP_SMS,
  BetaSessionServiceFactors.JSON_PROPERTY_OTP_EMAIL
})
@javax.annotation.Generated(value = "io.github.mridang.codegen.generators.java.BetterJavaCodegen", comments = "Generator version: 7.14.0")
public class BetaSessionServiceFactors {
  public static final String JSON_PROPERTY_USER = "user";
  @javax.annotation.Nullable
  private BetaSessionServiceUserFactor user;

  public static final String JSON_PROPERTY_PASSWORD = "password";
  @javax.annotation.Nullable
  private BetaSessionServicePasswordFactor password;

  public static final String JSON_PROPERTY_WEB_AUTH_N = "webAuthN";
  @javax.annotation.Nullable
  private BetaSessionServiceWebAuthNFactor webAuthN;

  public static final String JSON_PROPERTY_INTENT = "intent";
  @javax.annotation.Nullable
  private BetaSessionServiceIntentFactor intent;

  public static final String JSON_PROPERTY_TOTP = "totp";
  @javax.annotation.Nullable
  private BetaSessionServiceTOTPFactor totp;

  public static final String JSON_PROPERTY_OTP_SMS = "otpSms";
  @javax.annotation.Nullable
  private BetaSessionServiceOTPFactor otpSms;

  public static final String JSON_PROPERTY_OTP_EMAIL = "otpEmail";
  @javax.annotation.Nullable
  private BetaSessionServiceOTPFactor otpEmail;

  public BetaSessionServiceFactors() {
  }

  public BetaSessionServiceFactors user(@javax.annotation.Nullable BetaSessionServiceUserFactor user) {
    
    this.user = user;
    return this;
  }

  /**
   * Get user
   * @return user
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BetaSessionServiceUserFactor getUser() {
    return user;
  }


  @JsonProperty(JSON_PROPERTY_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUser(@javax.annotation.Nullable BetaSessionServiceUserFactor user) {
    this.user = user;
  }

  public BetaSessionServiceFactors password(@javax.annotation.Nullable BetaSessionServicePasswordFactor password) {
    
    this.password = password;
    return this;
  }

  /**
   * Get password
   * @return password
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BetaSessionServicePasswordFactor getPassword() {
    return password;
  }


  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPassword(@javax.annotation.Nullable BetaSessionServicePasswordFactor password) {
    this.password = password;
  }

  public BetaSessionServiceFactors webAuthN(@javax.annotation.Nullable BetaSessionServiceWebAuthNFactor webAuthN) {
    
    this.webAuthN = webAuthN;
    return this;
  }

  /**
   * Get webAuthN
   * @return webAuthN
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WEB_AUTH_N)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BetaSessionServiceWebAuthNFactor getWebAuthN() {
    return webAuthN;
  }


  @JsonProperty(JSON_PROPERTY_WEB_AUTH_N)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWebAuthN(@javax.annotation.Nullable BetaSessionServiceWebAuthNFactor webAuthN) {
    this.webAuthN = webAuthN;
  }

  public BetaSessionServiceFactors intent(@javax.annotation.Nullable BetaSessionServiceIntentFactor intent) {
    
    this.intent = intent;
    return this;
  }

  /**
   * Get intent
   * @return intent
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INTENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BetaSessionServiceIntentFactor getIntent() {
    return intent;
  }


  @JsonProperty(JSON_PROPERTY_INTENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIntent(@javax.annotation.Nullable BetaSessionServiceIntentFactor intent) {
    this.intent = intent;
  }

  public BetaSessionServiceFactors totp(@javax.annotation.Nullable BetaSessionServiceTOTPFactor totp) {
    
    this.totp = totp;
    return this;
  }

  /**
   * Get totp
   * @return totp
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BetaSessionServiceTOTPFactor getTotp() {
    return totp;
  }


  @JsonProperty(JSON_PROPERTY_TOTP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotp(@javax.annotation.Nullable BetaSessionServiceTOTPFactor totp) {
    this.totp = totp;
  }

  public BetaSessionServiceFactors otpSms(@javax.annotation.Nullable BetaSessionServiceOTPFactor otpSms) {
    
    this.otpSms = otpSms;
    return this;
  }

  /**
   * Get otpSms
   * @return otpSms
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OTP_SMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BetaSessionServiceOTPFactor getOtpSms() {
    return otpSms;
  }


  @JsonProperty(JSON_PROPERTY_OTP_SMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOtpSms(@javax.annotation.Nullable BetaSessionServiceOTPFactor otpSms) {
    this.otpSms = otpSms;
  }

  public BetaSessionServiceFactors otpEmail(@javax.annotation.Nullable BetaSessionServiceOTPFactor otpEmail) {
    
    this.otpEmail = otpEmail;
    return this;
  }

  /**
   * Get otpEmail
   * @return otpEmail
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OTP_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BetaSessionServiceOTPFactor getOtpEmail() {
    return otpEmail;
  }


  @JsonProperty(JSON_PROPERTY_OTP_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOtpEmail(@javax.annotation.Nullable BetaSessionServiceOTPFactor otpEmail) {
    this.otpEmail = otpEmail;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BetaSessionServiceFactors betaSessionServiceFactors = (BetaSessionServiceFactors) o;
    return Objects.equals(this.user, betaSessionServiceFactors.user) &&
        Objects.equals(this.password, betaSessionServiceFactors.password) &&
        Objects.equals(this.webAuthN, betaSessionServiceFactors.webAuthN) &&
        Objects.equals(this.intent, betaSessionServiceFactors.intent) &&
        Objects.equals(this.totp, betaSessionServiceFactors.totp) &&
        Objects.equals(this.otpSms, betaSessionServiceFactors.otpSms) &&
        Objects.equals(this.otpEmail, betaSessionServiceFactors.otpEmail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(user, password, webAuthN, intent, totp, otpSms, otpEmail);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BetaSessionServiceFactors {\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    webAuthN: ").append(toIndentedString(webAuthN)).append("\n");
    sb.append("    intent: ").append(toIndentedString(intent)).append("\n");
    sb.append("    totp: ").append(toIndentedString(totp)).append("\n");
    sb.append("    otpSms: ").append(toIndentedString(otpSms)).append("\n");
    sb.append("    otpEmail: ").append(toIndentedString(otpEmail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `user` to the URL query string
    if (getUser() != null) {
      joiner.add(getUser().toUrlQueryString(prefix + "user" + suffix));
    }

    // add `password` to the URL query string
    if (getPassword() != null) {
      joiner.add(getPassword().toUrlQueryString(prefix + "password" + suffix));
    }

    // add `webAuthN` to the URL query string
    if (getWebAuthN() != null) {
      joiner.add(getWebAuthN().toUrlQueryString(prefix + "webAuthN" + suffix));
    }

    // add `intent` to the URL query string
    if (getIntent() != null) {
      joiner.add(getIntent().toUrlQueryString(prefix + "intent" + suffix));
    }

    // add `totp` to the URL query string
    if (getTotp() != null) {
      joiner.add(getTotp().toUrlQueryString(prefix + "totp" + suffix));
    }

    // add `otpSms` to the URL query string
    if (getOtpSms() != null) {
      joiner.add(getOtpSms().toUrlQueryString(prefix + "otpSms" + suffix));
    }

    // add `otpEmail` to the URL query string
    if (getOtpEmail() != null) {
      joiner.add(getOtpEmail().toUrlQueryString(prefix + "otpEmail" + suffix));
    }

    return joiner.toString();
  }

}

