/*
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zitadel.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zitadel.model.BetaUserServiceValue;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * BetaUserServiceVerifyPasskeyRegistrationRequest
 */
@JsonPropertyOrder({
  BetaUserServiceVerifyPasskeyRegistrationRequest.JSON_PROPERTY_USER_ID,
  BetaUserServiceVerifyPasskeyRegistrationRequest.JSON_PROPERTY_PASSKEY_ID,
  BetaUserServiceVerifyPasskeyRegistrationRequest.JSON_PROPERTY_PUBLIC_KEY_CREDENTIAL,
  BetaUserServiceVerifyPasskeyRegistrationRequest.JSON_PROPERTY_PASSKEY_NAME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class BetaUserServiceVerifyPasskeyRegistrationRequest {
  public static final String JSON_PROPERTY_USER_ID = "userId";
  @javax.annotation.Nonnull
  private String userId;

  public static final String JSON_PROPERTY_PASSKEY_ID = "passkeyId";
  @javax.annotation.Nonnull
  private String passkeyId;

  public static final String JSON_PROPERTY_PUBLIC_KEY_CREDENTIAL = "publicKeyCredential";
  @javax.annotation.Nonnull
  private Map<String, BetaUserServiceValue> publicKeyCredential = new HashMap<>();

  public static final String JSON_PROPERTY_PASSKEY_NAME = "passkeyName";
  @javax.annotation.Nonnull
  private String passkeyName;

  public BetaUserServiceVerifyPasskeyRegistrationRequest() {
  }

  public BetaUserServiceVerifyPasskeyRegistrationRequest userId(@javax.annotation.Nonnull String userId) {
    
    this.userId = userId;
    return this;
  }

  /**
   * Get userId
   * @return userId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUserId() {
    return userId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUserId(@javax.annotation.Nonnull String userId) {
    this.userId = userId;
  }

  public BetaUserServiceVerifyPasskeyRegistrationRequest passkeyId(@javax.annotation.Nonnull String passkeyId) {
    
    this.passkeyId = passkeyId;
    return this;
  }

  /**
   * Get passkeyId
   * @return passkeyId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PASSKEY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPasskeyId() {
    return passkeyId;
  }


  @JsonProperty(JSON_PROPERTY_PASSKEY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPasskeyId(@javax.annotation.Nonnull String passkeyId) {
    this.passkeyId = passkeyId;
  }

  public BetaUserServiceVerifyPasskeyRegistrationRequest publicKeyCredential(@javax.annotation.Nonnull Map<String, BetaUserServiceValue> publicKeyCredential) {
    
    this.publicKeyCredential = publicKeyCredential;
    return this;
  }

  public BetaUserServiceVerifyPasskeyRegistrationRequest putPublicKeyCredentialItem(String key, BetaUserServiceValue publicKeyCredentialItem) {
    this.publicKeyCredential.put(key, publicKeyCredentialItem);
    return this;
  }

  /**
   * &#x60;Struct&#x60; represents a structured data value, consisting of fields  which map to dynamically typed values. In some languages, &#x60;Struct&#x60;  might be supported by a native representation. For example, in  scripting languages like JS a struct is represented as an  object. The details of that representation are described together  with the proto support for the language.   The JSON representation for &#x60;Struct&#x60; is JSON object.
   * @return publicKeyCredential
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PUBLIC_KEY_CREDENTIAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Map<String, BetaUserServiceValue> getPublicKeyCredential() {
    return publicKeyCredential;
  }


  @JsonProperty(JSON_PROPERTY_PUBLIC_KEY_CREDENTIAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPublicKeyCredential(@javax.annotation.Nonnull Map<String, BetaUserServiceValue> publicKeyCredential) {
    this.publicKeyCredential = publicKeyCredential;
  }

  public BetaUserServiceVerifyPasskeyRegistrationRequest passkeyName(@javax.annotation.Nonnull String passkeyName) {
    
    this.passkeyName = passkeyName;
    return this;
  }

  /**
   * Get passkeyName
   * @return passkeyName
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PASSKEY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPasskeyName() {
    return passkeyName;
  }


  @JsonProperty(JSON_PROPERTY_PASSKEY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPasskeyName(@javax.annotation.Nonnull String passkeyName) {
    this.passkeyName = passkeyName;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BetaUserServiceVerifyPasskeyRegistrationRequest betaUserServiceVerifyPasskeyRegistrationRequest = (BetaUserServiceVerifyPasskeyRegistrationRequest) o;
    return Objects.equals(this.userId, betaUserServiceVerifyPasskeyRegistrationRequest.userId) &&
        Objects.equals(this.passkeyId, betaUserServiceVerifyPasskeyRegistrationRequest.passkeyId) &&
        Objects.equals(this.publicKeyCredential, betaUserServiceVerifyPasskeyRegistrationRequest.publicKeyCredential) &&
        Objects.equals(this.passkeyName, betaUserServiceVerifyPasskeyRegistrationRequest.passkeyName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, passkeyId, publicKeyCredential, passkeyName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BetaUserServiceVerifyPasskeyRegistrationRequest {\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    passkeyId: ").append(toIndentedString(passkeyId)).append("\n");
    sb.append("    publicKeyCredential: ").append(toIndentedString(publicKeyCredential)).append("\n");
    sb.append("    passkeyName: ").append(toIndentedString(passkeyName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `userId` to the URL query string
    if (getUserId() != null) {
      try {
        joiner.add(String.format("%suserId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getUserId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `passkeyId` to the URL query string
    if (getPasskeyId() != null) {
      try {
        joiner.add(String.format("%spasskeyId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPasskeyId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `publicKeyCredential` to the URL query string
    if (getPublicKeyCredential() != null) {
      for (String _key : getPublicKeyCredential().keySet()) {
        if (getPublicKeyCredential().get(_key) != null) {
          joiner.add(getPublicKeyCredential().get(_key).toUrlQueryString(String.format("%spublicKeyCredential%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix))));
        }
      }
    }

    // add `passkeyName` to the URL query string
    if (getPasskeyName() != null) {
      try {
        joiner.add(String.format("%spasskeyName%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPasskeyName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

