// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating
// with your Zitadel environment. This SDK enables you to handle resources, settings, and
// configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

package com.zitadel.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import javax.annotation.Nullable;

/** IdentityProviderServiceJWTConfig. */
@SuppressWarnings({
  "checkstyle:SummaryJavadoc",
  "checkstyle:JavadocParagraph",
  "checkstyle:SingleLineJavadoc",
  "checkstyle:RequireEmptyLineBeforeBlockTagGroup",
  "checkstyle:NonEmptyAtclauseDescription",
  "checkstyle:JavadocTagContinuationIndentation",
  "checkstyle:AtclauseOrder",
  "checkstyle:InvalidJavadocPosition",
  "checkstyle:AbbreviationAsWordInName",
  "checkstyle:MemberName",
  "checkstyle:OverloadMethodsDeclarationOrder",
  "checkstyle:VariableDeclarationUsageDistance",
  "checkstyle:ConstructorsDeclarationGrouping"
})
public class IdentityProviderServiceJWTConfig {

  /**
   * The endpoint where the JWT can be extracted.
   *
   * <p>Example: {@code null}
   */
  @JsonProperty("jwtEndpoint")
  @Nullable
  public String jwtEndpoint;

  /**
   * The issuer of the JWT (for validation).
   *
   * <p>Example: {@code null}
   */
  @JsonProperty("issuer")
  @Nullable
  public String issuer;

  /**
   * The endpoint to the key (JWK) which is used to sign the JWT with.
   *
   * <p>Example: {@code null}
   */
  @JsonProperty("keysEndpoint")
  @Nullable
  public String keysEndpoint;

  /**
   * The name of the header where the JWT is sent in, default is authorization.
   *
   * <p>Example: {@code null}
   */
  @JsonProperty("headerName")
  @Nullable
  public String headerName;

  /** Creates an empty instance. */
  public IdentityProviderServiceJWTConfig() {}

  /* Value-equality based on all declared fields. Generated so model
   * instances work correctly as Set/Map keys and in test assertions.
   * Uses pattern-matching `instanceof other` (Java 16+) — required by
   * Error Prone's PatternMatchingInstanceof rule and avoids the
   * EqualsGetClass warning that plain getClass() comparison triggers. */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof IdentityProviderServiceJWTConfig other)) {
      return false;
    }
    return java.util.Objects.equals(this.jwtEndpoint, other.jwtEndpoint)
        && java.util.Objects.equals(this.issuer, other.issuer)
        && java.util.Objects.equals(this.keysEndpoint, other.keysEndpoint)
        && java.util.Objects.equals(this.headerName, other.headerName);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(jwtEndpoint, issuer, keysEndpoint, headerName);
  }
}
