/*
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zitadel.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.openapitools.jackson.nullable.JsonNullable;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.Arrays;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * IdentityProviderServiceSAMLConfig
 */
@JsonPropertyOrder({
  IdentityProviderServiceSAMLConfig.JSON_PROPERTY_METADATA_XML,
  IdentityProviderServiceSAMLConfig.JSON_PROPERTY_BINDING,
  IdentityProviderServiceSAMLConfig.JSON_PROPERTY_WITH_SIGNED_REQUEST,
  IdentityProviderServiceSAMLConfig.JSON_PROPERTY_NAME_ID_FORMAT,
  IdentityProviderServiceSAMLConfig.JSON_PROPERTY_TRANSIENT_MAPPING_ATTRIBUTE_NAME,
  IdentityProviderServiceSAMLConfig.JSON_PROPERTY_FEDERATED_LOGOUT_ENABLED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class IdentityProviderServiceSAMLConfig {
  public static final String JSON_PROPERTY_METADATA_XML = "metadataXml";
  @javax.annotation.Nullable
  private byte[] metadataXml;

  public static final String JSON_PROPERTY_BINDING = "binding";
  @javax.annotation.Nullable
  private IdentityProviderServiceSAMLBinding binding;

  public static final String JSON_PROPERTY_WITH_SIGNED_REQUEST = "withSignedRequest";
  @javax.annotation.Nullable
  private Boolean withSignedRequest;

  public static final String JSON_PROPERTY_NAME_ID_FORMAT = "nameIdFormat";
  @javax.annotation.Nullable
  private IdentityProviderServiceSAMLNameIDFormat nameIdFormat;

  public static final String JSON_PROPERTY_TRANSIENT_MAPPING_ATTRIBUTE_NAME = "transientMappingAttributeName";
  @javax.annotation.Nullable
  private JsonNullable<String> transientMappingAttributeName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_FEDERATED_LOGOUT_ENABLED = "federatedLogoutEnabled";
  @javax.annotation.Nullable
  private JsonNullable<Boolean> federatedLogoutEnabled = JsonNullable.<Boolean>undefined();

  public IdentityProviderServiceSAMLConfig() {
  }

  public IdentityProviderServiceSAMLConfig metadataXml(@javax.annotation.Nullable byte[] metadataXml) {

    this.metadataXml = metadataXml;
    return this;
  }

  /**
   * Metadata of the SAML identity provider.
   * @return metadataXml
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_METADATA_XML)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public byte[] getMetadataXml() {
    return metadataXml;
  }


  @JsonProperty(JSON_PROPERTY_METADATA_XML)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadataXml(@javax.annotation.Nullable byte[] metadataXml) {
    this.metadataXml = metadataXml;
  }

  public IdentityProviderServiceSAMLConfig binding(@javax.annotation.Nullable IdentityProviderServiceSAMLBinding binding) {

    this.binding = binding;
    return this;
  }

  /**
   * Get binding
   * @return binding
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BINDING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public IdentityProviderServiceSAMLBinding getBinding() {
    return binding;
  }


  @JsonProperty(JSON_PROPERTY_BINDING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBinding(@javax.annotation.Nullable IdentityProviderServiceSAMLBinding binding) {
    this.binding = binding;
  }

  public IdentityProviderServiceSAMLConfig withSignedRequest(@javax.annotation.Nullable Boolean withSignedRequest) {

    this.withSignedRequest = withSignedRequest;
    return this;
  }

  /**
   * Boolean which defines if the authentication requests are signed.
   * @return withSignedRequest
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WITH_SIGNED_REQUEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getWithSignedRequest() {
    return withSignedRequest;
  }


  @JsonProperty(JSON_PROPERTY_WITH_SIGNED_REQUEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWithSignedRequest(@javax.annotation.Nullable Boolean withSignedRequest) {
    this.withSignedRequest = withSignedRequest;
  }

  public IdentityProviderServiceSAMLConfig nameIdFormat(@javax.annotation.Nullable IdentityProviderServiceSAMLNameIDFormat nameIdFormat) {

    this.nameIdFormat = nameIdFormat;
    return this;
  }

  /**
   * Get nameIdFormat
   * @return nameIdFormat
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME_ID_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public IdentityProviderServiceSAMLNameIDFormat getNameIdFormat() {
    return nameIdFormat;
  }


  @JsonProperty(JSON_PROPERTY_NAME_ID_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNameIdFormat(@javax.annotation.Nullable IdentityProviderServiceSAMLNameIDFormat nameIdFormat) {
    this.nameIdFormat = nameIdFormat;
  }

  public IdentityProviderServiceSAMLConfig transientMappingAttributeName(@javax.annotation.Nullable String transientMappingAttributeName) {
    this.transientMappingAttributeName = JsonNullable.<String>of(transientMappingAttributeName);

    return this;
  }

  /**
   * Optional name of the attribute, which will be used to map the user  in case the nameid-format returned is  &#x60;urn:oasis:names:tc:SAML:2.0:nameid-format:transient&#x60;.
   * @return transientMappingAttributeName
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getTransientMappingAttributeName() {
        return transientMappingAttributeName.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TRANSIENT_MAPPING_ATTRIBUTE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getTransientMappingAttributeName_JsonNullable() {
    return transientMappingAttributeName;
  }

  @JsonProperty(JSON_PROPERTY_TRANSIENT_MAPPING_ATTRIBUTE_NAME)
  public void setTransientMappingAttributeName_JsonNullable(JsonNullable<String> transientMappingAttributeName) {
    this.transientMappingAttributeName = transientMappingAttributeName;
  }

  public void setTransientMappingAttributeName(@javax.annotation.Nullable String transientMappingAttributeName) {
    this.transientMappingAttributeName = JsonNullable.<String>of(transientMappingAttributeName);
  }

  public IdentityProviderServiceSAMLConfig federatedLogoutEnabled(@javax.annotation.Nullable Boolean federatedLogoutEnabled) {
    this.federatedLogoutEnabled = JsonNullable.<Boolean>of(federatedLogoutEnabled);

    return this;
  }

  /**
   * Boolean weather federated logout is enabled. If enabled, ZITADEL will send a logout request to the identity provider,  if the user terminates the session in ZITADEL. Be sure to provide a SLO endpoint as part of the metadata.
   * @return federatedLogoutEnabled
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public Boolean getFederatedLogoutEnabled() {
        return federatedLogoutEnabled.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_FEDERATED_LOGOUT_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getFederatedLogoutEnabled_JsonNullable() {
    return federatedLogoutEnabled;
  }

  @JsonProperty(JSON_PROPERTY_FEDERATED_LOGOUT_ENABLED)
  public void setFederatedLogoutEnabled_JsonNullable(JsonNullable<Boolean> federatedLogoutEnabled) {
    this.federatedLogoutEnabled = federatedLogoutEnabled;
  }

  public void setFederatedLogoutEnabled(@javax.annotation.Nullable Boolean federatedLogoutEnabled) {
    this.federatedLogoutEnabled = JsonNullable.<Boolean>of(federatedLogoutEnabled);
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IdentityProviderServiceSAMLConfig identityProviderServiceSAMLConfig = (IdentityProviderServiceSAMLConfig) o;
    return Arrays.equals(this.metadataXml, identityProviderServiceSAMLConfig.metadataXml) &&
        Objects.equals(this.binding, identityProviderServiceSAMLConfig.binding) &&
        Objects.equals(this.withSignedRequest, identityProviderServiceSAMLConfig.withSignedRequest) &&
        Objects.equals(this.nameIdFormat, identityProviderServiceSAMLConfig.nameIdFormat) &&
        equalsNullable(this.transientMappingAttributeName, identityProviderServiceSAMLConfig.transientMappingAttributeName) &&
        equalsNullable(this.federatedLogoutEnabled, identityProviderServiceSAMLConfig.federatedLogoutEnabled);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(Arrays.hashCode(metadataXml), binding, withSignedRequest, nameIdFormat, hashCodeNullable(transientMappingAttributeName), hashCodeNullable(federatedLogoutEnabled));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IdentityProviderServiceSAMLConfig {\n");
    sb.append("    metadataXml: ").append(toIndentedString(metadataXml)).append("\n");
    sb.append("    binding: ").append(toIndentedString(binding)).append("\n");
    sb.append("    withSignedRequest: ").append(toIndentedString(withSignedRequest)).append("\n");
    sb.append("    nameIdFormat: ").append(toIndentedString(nameIdFormat)).append("\n");
    sb.append("    transientMappingAttributeName: ").append(toIndentedString(transientMappingAttributeName)).append("\n");
    sb.append("    federatedLogoutEnabled: ").append(toIndentedString(federatedLogoutEnabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `metadataXml` to the URL query string
    if (getMetadataXml() != null) {
      try {
        joiner.add(String.format("%smetadataXml%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMetadataXml()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `binding` to the URL query string
    if (getBinding() != null) {
      try {
        joiner.add(String.format("%sbinding%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getBinding()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `withSignedRequest` to the URL query string
    if (getWithSignedRequest() != null) {
      try {
        joiner.add(String.format("%swithSignedRequest%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getWithSignedRequest()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `nameIdFormat` to the URL query string
    if (getNameIdFormat() != null) {
      try {
        joiner.add(String.format("%snameIdFormat%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getNameIdFormat()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `transientMappingAttributeName` to the URL query string
    if (getTransientMappingAttributeName() != null) {
      try {
        joiner.add(String.format("%stransientMappingAttributeName%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTransientMappingAttributeName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `federatedLogoutEnabled` to the URL query string
    if (getFederatedLogoutEnabled() != null) {
      try {
        joiner.add(String.format("%sfederatedLogoutEnabled%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFederatedLogoutEnabled()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}
