/*
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zitadel.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * InstanceServiceRemoveCustomDomainRequest
 */
@JsonPropertyOrder({
  InstanceServiceRemoveCustomDomainRequest.JSON_PROPERTY_INSTANCE_ID,
  InstanceServiceRemoveCustomDomainRequest.JSON_PROPERTY_CUSTOM_DOMAIN
})
@javax.annotation.Generated(value = "io.github.mridang.codegen.generators.java.BetterJavaCodegen", comments = "Generator version: 7.14.0")
public class InstanceServiceRemoveCustomDomainRequest {
  public static final String JSON_PROPERTY_INSTANCE_ID = "instanceId";
  @javax.annotation.Nullable
  private String instanceId;

  public static final String JSON_PROPERTY_CUSTOM_DOMAIN = "customDomain";
  @javax.annotation.Nullable
  private String customDomain;

  public InstanceServiceRemoveCustomDomainRequest() {
  }

  public InstanceServiceRemoveCustomDomainRequest instanceId(@javax.annotation.Nullable String instanceId) {
    
    this.instanceId = instanceId;
    return this;
  }

  /**
   * InstanceID is the unique ID of the instance from which the domain will be removed.
   * @return instanceId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INSTANCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInstanceId() {
    return instanceId;
  }


  @JsonProperty(JSON_PROPERTY_INSTANCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInstanceId(@javax.annotation.Nullable String instanceId) {
    this.instanceId = instanceId;
  }

  public InstanceServiceRemoveCustomDomainRequest customDomain(@javax.annotation.Nullable String customDomain) {
    
    this.customDomain = customDomain;
    return this;
  }

  /**
   * CustomDomain is the the domain to remove from the instance.
   * @return customDomain
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUSTOM_DOMAIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCustomDomain() {
    return customDomain;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOM_DOMAIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomDomain(@javax.annotation.Nullable String customDomain) {
    this.customDomain = customDomain;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InstanceServiceRemoveCustomDomainRequest instanceServiceRemoveCustomDomainRequest = (InstanceServiceRemoveCustomDomainRequest) o;
    return Objects.equals(this.instanceId, instanceServiceRemoveCustomDomainRequest.instanceId) &&
        Objects.equals(this.customDomain, instanceServiceRemoveCustomDomainRequest.customDomain);
  }

  @Override
  public int hashCode() {
    return Objects.hash(instanceId, customDomain);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InstanceServiceRemoveCustomDomainRequest {\n");
    sb.append("    instanceId: ").append(toIndentedString(instanceId)).append("\n");
    sb.append("    customDomain: ").append(toIndentedString(customDomain)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `instanceId` to the URL query string
    if (getInstanceId() != null) {
      try {
        joiner.add(String.format("%sinstanceId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getInstanceId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `customDomain` to the URL query string
    if (getCustomDomain() != null) {
      try {
        joiner.add(String.format("%scustomDomain%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCustomDomain()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

