// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating
// with your Zitadel environment. This SDK enables you to handle resources, settings, and
// configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

package com.zitadel.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import javax.annotation.Nullable;

/** InstanceServiceCustomDomainFilter. */
@SuppressWarnings({
  "checkstyle:SummaryJavadoc",
  "checkstyle:JavadocParagraph",
  "checkstyle:SingleLineJavadoc",
  "checkstyle:RequireEmptyLineBeforeBlockTagGroup",
  "checkstyle:NonEmptyAtclauseDescription",
  "checkstyle:JavadocTagContinuationIndentation",
  "checkstyle:AtclauseOrder",
  "checkstyle:InvalidJavadocPosition",
  "checkstyle:AbbreviationAsWordInName",
  "checkstyle:MemberName",
  "checkstyle:OverloadMethodsDeclarationOrder",
  "checkstyle:VariableDeclarationUsageDistance",
  "checkstyle:ConstructorsDeclarationGrouping"
})
public class InstanceServiceCustomDomainFilter {

  /** Example: {@code null} */
  @JsonProperty("domainFilter")
  @Nullable
  public InstanceServiceDomainFilter domainFilter;

  /**
   * Filter whether the domain is auto-generated.
   *
   * <p>Example: {@code null}
   */
  @JsonProperty("generatedFilter")
  @Nullable
  public Boolean generatedFilter;

  /**
   * Filter whether the domain is the primary domain of the instance.
   *
   * <p>Example: {@code null}
   */
  @JsonProperty("primaryFilter")
  @Nullable
  public Boolean primaryFilter;

  /** Creates an empty instance. */
  public InstanceServiceCustomDomainFilter() {}

  /* Value-equality based on all declared fields. Generated so model
   * instances work correctly as Set/Map keys and in test assertions.
   * Uses pattern-matching `instanceof other` (Java 16+) — required by
   * Error Prone's PatternMatchingInstanceof rule and avoids the
   * EqualsGetClass warning that plain getClass() comparison triggers. */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof InstanceServiceCustomDomainFilter other)) {
      return false;
    }
    return java.util.Objects.equals(this.domainFilter, other.domainFilter)
        && java.util.Objects.equals(this.generatedFilter, other.generatedFilter)
        && java.util.Objects.equals(this.primaryFilter, other.primaryFilter);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(domainFilter, generatedFilter, primaryFilter);
  }
}
