/*
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zitadel.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zitadel.model.SAMLServiceAuthorizationError;
import com.zitadel.model.SAMLServicePostResponse;
import com.zitadel.model.SAMLServiceSession;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * NoOp200Response7
 */
@JsonPropertyOrder({
  NoOp200Response7.JSON_PROPERTY_32657D173E6D45C6_B95A57F0927E4246,
  NoOp200Response7.JSON_PROPERTY_A730FAA0963C46F7_B1B3_A7B2D884D7C8,
  NoOp200Response7.JSON_PROPERTY_E07BFD13_BCE54FD7_BE030E46462E5DEA,
  NoOp200Response7.JSON_PROPERTY_E3919A44_F603416E86E31ABCC6493639
})
@JsonTypeName("NoOp_200_response_7")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class NoOp200Response7 {
  public static final String JSON_PROPERTY_32657D173E6D45C6_B95A57F0927E4246 = "32657d17-3e6d-45c6-b95a-57f0927e4246";
  @javax.annotation.Nullable
  private SAMLServiceAuthorizationError _32657d173e6d45c6B95a57f0927e4246;

  public static final String JSON_PROPERTY_A730FAA0963C46F7_B1B3_A7B2D884D7C8 = "a730faa0-963c-46f7-b1b3-a7b2d884d7c8";
  @javax.annotation.Nullable
  private SAMLServicePostResponse a730faa0963c46f7B1b3A7b2d884d7c8;

  public static final String JSON_PROPERTY_E07BFD13_BCE54FD7_BE030E46462E5DEA = "e07bfd13-bce5-4fd7-be03-0e46462e5dea";
  @javax.annotation.Nullable
  private Object e07bfd13Bce54fd7Be030e46462e5dea;

  public static final String JSON_PROPERTY_E3919A44_F603416E86E31ABCC6493639 = "e3919a44-f603-416e-86e3-1abcc6493639";
  @javax.annotation.Nullable
  private SAMLServiceSession e3919a44F603416e86e31abcc6493639;

  public NoOp200Response7() {
  }

  public NoOp200Response7 _32657d173e6d45c6B95a57f0927e4246(@javax.annotation.Nullable SAMLServiceAuthorizationError _32657d173e6d45c6B95a57f0927e4246) {
    
    this._32657d173e6d45c6B95a57f0927e4246 = _32657d173e6d45c6B95a57f0927e4246;
    return this;
  }

  /**
   * Get _32657d173e6d45c6B95a57f0927e4246
   * @return _32657d173e6d45c6B95a57f0927e4246
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_32657D173E6D45C6_B95A57F0927E4246)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SAMLServiceAuthorizationError get32657d173e6d45c6B95a57f0927e4246() {
    return _32657d173e6d45c6B95a57f0927e4246;
  }


  @JsonProperty(JSON_PROPERTY_32657D173E6D45C6_B95A57F0927E4246)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void set32657d173e6d45c6B95a57f0927e4246(@javax.annotation.Nullable SAMLServiceAuthorizationError _32657d173e6d45c6B95a57f0927e4246) {
    this._32657d173e6d45c6B95a57f0927e4246 = _32657d173e6d45c6B95a57f0927e4246;
  }

  public NoOp200Response7 a730faa0963c46f7B1b3A7b2d884d7c8(@javax.annotation.Nullable SAMLServicePostResponse a730faa0963c46f7B1b3A7b2d884d7c8) {
    
    this.a730faa0963c46f7B1b3A7b2d884d7c8 = a730faa0963c46f7B1b3A7b2d884d7c8;
    return this;
  }

  /**
   * Get a730faa0963c46f7B1b3A7b2d884d7c8
   * @return a730faa0963c46f7B1b3A7b2d884d7c8
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_A730FAA0963C46F7_B1B3_A7B2D884D7C8)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SAMLServicePostResponse getA730faa0963c46f7B1b3A7b2d884d7c8() {
    return a730faa0963c46f7B1b3A7b2d884d7c8;
  }


  @JsonProperty(JSON_PROPERTY_A730FAA0963C46F7_B1B3_A7B2D884D7C8)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setA730faa0963c46f7B1b3A7b2d884d7c8(@javax.annotation.Nullable SAMLServicePostResponse a730faa0963c46f7B1b3A7b2d884d7c8) {
    this.a730faa0963c46f7B1b3A7b2d884d7c8 = a730faa0963c46f7B1b3A7b2d884d7c8;
  }

  public NoOp200Response7 e07bfd13Bce54fd7Be030e46462e5dea(@javax.annotation.Nullable Object e07bfd13Bce54fd7Be030e46462e5dea) {
    
    this.e07bfd13Bce54fd7Be030e46462e5dea = e07bfd13Bce54fd7Be030e46462e5dea;
    return this;
  }

  /**
   * Get e07bfd13Bce54fd7Be030e46462e5dea
   * @return e07bfd13Bce54fd7Be030e46462e5dea
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_E07BFD13_BCE54FD7_BE030E46462E5DEA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getE07bfd13Bce54fd7Be030e46462e5dea() {
    return e07bfd13Bce54fd7Be030e46462e5dea;
  }


  @JsonProperty(JSON_PROPERTY_E07BFD13_BCE54FD7_BE030E46462E5DEA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setE07bfd13Bce54fd7Be030e46462e5dea(@javax.annotation.Nullable Object e07bfd13Bce54fd7Be030e46462e5dea) {
    this.e07bfd13Bce54fd7Be030e46462e5dea = e07bfd13Bce54fd7Be030e46462e5dea;
  }

  public NoOp200Response7 e3919a44F603416e86e31abcc6493639(@javax.annotation.Nullable SAMLServiceSession e3919a44F603416e86e31abcc6493639) {
    
    this.e3919a44F603416e86e31abcc6493639 = e3919a44F603416e86e31abcc6493639;
    return this;
  }

  /**
   * Get e3919a44F603416e86e31abcc6493639
   * @return e3919a44F603416e86e31abcc6493639
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_E3919A44_F603416E86E31ABCC6493639)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SAMLServiceSession getE3919a44F603416e86e31abcc6493639() {
    return e3919a44F603416e86e31abcc6493639;
  }


  @JsonProperty(JSON_PROPERTY_E3919A44_F603416E86E31ABCC6493639)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setE3919a44F603416e86e31abcc6493639(@javax.annotation.Nullable SAMLServiceSession e3919a44F603416e86e31abcc6493639) {
    this.e3919a44F603416e86e31abcc6493639 = e3919a44F603416e86e31abcc6493639;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NoOp200Response7 noOp200Response7 = (NoOp200Response7) o;
    return Objects.equals(this._32657d173e6d45c6B95a57f0927e4246, noOp200Response7._32657d173e6d45c6B95a57f0927e4246) &&
        Objects.equals(this.a730faa0963c46f7B1b3A7b2d884d7c8, noOp200Response7.a730faa0963c46f7B1b3A7b2d884d7c8) &&
        Objects.equals(this.e07bfd13Bce54fd7Be030e46462e5dea, noOp200Response7.e07bfd13Bce54fd7Be030e46462e5dea) &&
        Objects.equals(this.e3919a44F603416e86e31abcc6493639, noOp200Response7.e3919a44F603416e86e31abcc6493639);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_32657d173e6d45c6B95a57f0927e4246, a730faa0963c46f7B1b3A7b2d884d7c8, e07bfd13Bce54fd7Be030e46462e5dea, e3919a44F603416e86e31abcc6493639);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NoOp200Response7 {\n");
    sb.append("    _32657d173e6d45c6B95a57f0927e4246: ").append(toIndentedString(_32657d173e6d45c6B95a57f0927e4246)).append("\n");
    sb.append("    a730faa0963c46f7B1b3A7b2d884d7c8: ").append(toIndentedString(a730faa0963c46f7B1b3A7b2d884d7c8)).append("\n");
    sb.append("    e07bfd13Bce54fd7Be030e46462e5dea: ").append(toIndentedString(e07bfd13Bce54fd7Be030e46462e5dea)).append("\n");
    sb.append("    e3919a44F603416e86e31abcc6493639: ").append(toIndentedString(e3919a44F603416e86e31abcc6493639)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `32657d17-3e6d-45c6-b95a-57f0927e4246` to the URL query string
    if (get32657d173e6d45c6B95a57f0927e4246() != null) {
      joiner.add(get32657d173e6d45c6B95a57f0927e4246().toUrlQueryString(prefix + "32657d17-3e6d-45c6-b95a-57f0927e4246" + suffix));
    }

    // add `a730faa0-963c-46f7-b1b3-a7b2d884d7c8` to the URL query string
    if (getA730faa0963c46f7B1b3A7b2d884d7c8() != null) {
      joiner.add(getA730faa0963c46f7B1b3A7b2d884d7c8().toUrlQueryString(prefix + "a730faa0-963c-46f7-b1b3-a7b2d884d7c8" + suffix));
    }

    // add `e07bfd13-bce5-4fd7-be03-0e46462e5dea` to the URL query string
    if (getE07bfd13Bce54fd7Be030e46462e5dea() != null) {
      try {
        joiner.add(String.format("%se07bfd13-bce5-4fd7-be03-0e46462e5dea%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getE07bfd13Bce54fd7Be030e46462e5dea()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `e3919a44-f603-416e-86e3-1abcc6493639` to the URL query string
    if (getE3919a44F603416e86e31abcc6493639() != null) {
      joiner.add(getE3919a44F603416e86e31abcc6493639().toUrlQueryString(prefix + "e3919a44-f603-416e-86e3-1abcc6493639" + suffix));
    }

    return joiner.toString();
  }

}

