/*
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zitadel.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zitadel.model.BetaWebKeyServiceECDSA;
import com.zitadel.model.BetaWebKeyServiceRSA;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * NoOp200Response3
 */
@JsonPropertyOrder({
  NoOp200Response3.JSON_PROPERTY_1D6C34F6301B448084F7_A47BA35FA043,
  NoOp200Response3.JSON_PROPERTY_C784C732_A5F84ECD9896_EF41F41E5ECF,
  NoOp200Response3.JSON_PROPERTY_91669586A283405F9A5C4BE5098D7F3A
})
@JsonTypeName("NoOp_200_response_3")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class NoOp200Response3 {
  public static final String JSON_PROPERTY_1D6C34F6301B448084F7_A47BA35FA043 = "1d6c34f6-301b-4480-84f7-a47ba35fa043";
  @javax.annotation.Nullable
  private BetaWebKeyServiceECDSA _1d6c34f6301b448084f7A47ba35fa043;

  public static final String JSON_PROPERTY_C784C732_A5F84ECD9896_EF41F41E5ECF = "c784c732-a5f8-4ecd-9896-ef41f41e5ecf";
  @javax.annotation.Nullable
  private Object c784c732A5f84ecd9896Ef41f41e5ecf;

  public static final String JSON_PROPERTY_91669586A283405F9A5C4BE5098D7F3A = "91669586-a283-405f-9a5c-4be5098d7f3a";
  @javax.annotation.Nullable
  private BetaWebKeyServiceRSA _91669586a283405f9a5c4be5098d7f3a;

  public NoOp200Response3() {
  }

  public NoOp200Response3 _1d6c34f6301b448084f7A47ba35fa043(@javax.annotation.Nullable BetaWebKeyServiceECDSA _1d6c34f6301b448084f7A47ba35fa043) {
    
    this._1d6c34f6301b448084f7A47ba35fa043 = _1d6c34f6301b448084f7A47ba35fa043;
    return this;
  }

  /**
   * Get _1d6c34f6301b448084f7A47ba35fa043
   * @return _1d6c34f6301b448084f7A47ba35fa043
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_1D6C34F6301B448084F7_A47BA35FA043)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BetaWebKeyServiceECDSA get1d6c34f6301b448084f7A47ba35fa043() {
    return _1d6c34f6301b448084f7A47ba35fa043;
  }


  @JsonProperty(JSON_PROPERTY_1D6C34F6301B448084F7_A47BA35FA043)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void set1d6c34f6301b448084f7A47ba35fa043(@javax.annotation.Nullable BetaWebKeyServiceECDSA _1d6c34f6301b448084f7A47ba35fa043) {
    this._1d6c34f6301b448084f7A47ba35fa043 = _1d6c34f6301b448084f7A47ba35fa043;
  }

  public NoOp200Response3 c784c732A5f84ecd9896Ef41f41e5ecf(@javax.annotation.Nullable Object c784c732A5f84ecd9896Ef41f41e5ecf) {
    
    this.c784c732A5f84ecd9896Ef41f41e5ecf = c784c732A5f84ecd9896Ef41f41e5ecf;
    return this;
  }

  /**
   * Get c784c732A5f84ecd9896Ef41f41e5ecf
   * @return c784c732A5f84ecd9896Ef41f41e5ecf
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_C784C732_A5F84ECD9896_EF41F41E5ECF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getC784c732A5f84ecd9896Ef41f41e5ecf() {
    return c784c732A5f84ecd9896Ef41f41e5ecf;
  }


  @JsonProperty(JSON_PROPERTY_C784C732_A5F84ECD9896_EF41F41E5ECF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setC784c732A5f84ecd9896Ef41f41e5ecf(@javax.annotation.Nullable Object c784c732A5f84ecd9896Ef41f41e5ecf) {
    this.c784c732A5f84ecd9896Ef41f41e5ecf = c784c732A5f84ecd9896Ef41f41e5ecf;
  }

  public NoOp200Response3 _91669586a283405f9a5c4be5098d7f3a(@javax.annotation.Nullable BetaWebKeyServiceRSA _91669586a283405f9a5c4be5098d7f3a) {
    
    this._91669586a283405f9a5c4be5098d7f3a = _91669586a283405f9a5c4be5098d7f3a;
    return this;
  }

  /**
   * Get _91669586a283405f9a5c4be5098d7f3a
   * @return _91669586a283405f9a5c4be5098d7f3a
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_91669586A283405F9A5C4BE5098D7F3A)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BetaWebKeyServiceRSA get91669586a283405f9a5c4be5098d7f3a() {
    return _91669586a283405f9a5c4be5098d7f3a;
  }


  @JsonProperty(JSON_PROPERTY_91669586A283405F9A5C4BE5098D7F3A)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void set91669586a283405f9a5c4be5098d7f3a(@javax.annotation.Nullable BetaWebKeyServiceRSA _91669586a283405f9a5c4be5098d7f3a) {
    this._91669586a283405f9a5c4be5098d7f3a = _91669586a283405f9a5c4be5098d7f3a;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NoOp200Response3 noOp200Response3 = (NoOp200Response3) o;
    return Objects.equals(this._1d6c34f6301b448084f7A47ba35fa043, noOp200Response3._1d6c34f6301b448084f7A47ba35fa043) &&
        Objects.equals(this.c784c732A5f84ecd9896Ef41f41e5ecf, noOp200Response3.c784c732A5f84ecd9896Ef41f41e5ecf) &&
        Objects.equals(this._91669586a283405f9a5c4be5098d7f3a, noOp200Response3._91669586a283405f9a5c4be5098d7f3a);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_1d6c34f6301b448084f7A47ba35fa043, c784c732A5f84ecd9896Ef41f41e5ecf, _91669586a283405f9a5c4be5098d7f3a);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NoOp200Response3 {\n");
    sb.append("    _1d6c34f6301b448084f7A47ba35fa043: ").append(toIndentedString(_1d6c34f6301b448084f7A47ba35fa043)).append("\n");
    sb.append("    c784c732A5f84ecd9896Ef41f41e5ecf: ").append(toIndentedString(c784c732A5f84ecd9896Ef41f41e5ecf)).append("\n");
    sb.append("    _91669586a283405f9a5c4be5098d7f3a: ").append(toIndentedString(_91669586a283405f9a5c4be5098d7f3a)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `1d6c34f6-301b-4480-84f7-a47ba35fa043` to the URL query string
    if (get1d6c34f6301b448084f7A47ba35fa043() != null) {
      joiner.add(get1d6c34f6301b448084f7A47ba35fa043().toUrlQueryString(prefix + "1d6c34f6-301b-4480-84f7-a47ba35fa043" + suffix));
    }

    // add `c784c732-a5f8-4ecd-9896-ef41f41e5ecf` to the URL query string
    if (getC784c732A5f84ecd9896Ef41f41e5ecf() != null) {
      try {
        joiner.add(String.format("%sc784c732-a5f8-4ecd-9896-ef41f41e5ecf%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getC784c732A5f84ecd9896Ef41f41e5ecf()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `91669586-a283-405f-9a5c-4be5098d7f3a` to the URL query string
    if (get91669586a283405f9a5c4be5098d7f3a() != null) {
      joiner.add(get91669586a283405f9a5c4be5098d7f3a().toUrlQueryString(prefix + "91669586-a283-405f-9a5c-4be5098d7f3a" + suffix));
    }

    return joiner.toString();
  }

}

