/*
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zitadel.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zitadel.model.SessionServiceChecks;
import com.zitadel.model.SessionServiceRequestChallenges;
import com.zitadel.model.SessionServiceUserAgent;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * SessionServiceCreateSessionRequest1
 */
@JsonPropertyOrder({
  SessionServiceCreateSessionRequest1.JSON_PROPERTY_CHECKS,
  SessionServiceCreateSessionRequest1.JSON_PROPERTY_METADATA,
  SessionServiceCreateSessionRequest1.JSON_PROPERTY_CHALLENGES,
  SessionServiceCreateSessionRequest1.JSON_PROPERTY_USER_AGENT,
  SessionServiceCreateSessionRequest1.JSON_PROPERTY_LIFETIME
})
@JsonTypeName("SessionServiceCreateSessionRequest_1")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class SessionServiceCreateSessionRequest1 {
  public static final String JSON_PROPERTY_CHECKS = "checks";
  @javax.annotation.Nullable
  private SessionServiceChecks checks;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nullable
  private Map<String, byte[]> metadata = new HashMap<>();

  public static final String JSON_PROPERTY_CHALLENGES = "challenges";
  @javax.annotation.Nullable
  private SessionServiceRequestChallenges challenges;

  public static final String JSON_PROPERTY_USER_AGENT = "userAgent";
  @javax.annotation.Nullable
  private SessionServiceUserAgent userAgent;

  public static final String JSON_PROPERTY_LIFETIME = "lifetime";
  @javax.annotation.Nullable
  private String lifetime;

  public SessionServiceCreateSessionRequest1() {
  }

  public SessionServiceCreateSessionRequest1 checks(@javax.annotation.Nullable SessionServiceChecks checks) {
    
    this.checks = checks;
    return this;
  }

  /**
   * Get checks
   * @return checks
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHECKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SessionServiceChecks getChecks() {
    return checks;
  }


  @JsonProperty(JSON_PROPERTY_CHECKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChecks(@javax.annotation.Nullable SessionServiceChecks checks) {
    this.checks = checks;
  }

  public SessionServiceCreateSessionRequest1 metadata(@javax.annotation.Nullable Map<String, byte[]> metadata) {
    
    this.metadata = metadata;
    return this;
  }

  public SessionServiceCreateSessionRequest1 putMetadataItem(String key, byte[] metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

  /**
   * \&quot;custom key value list to be stored on the session\&quot;
   * @return metadata
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, byte[]> getMetadata() {
    return metadata;
  }


  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@javax.annotation.Nullable Map<String, byte[]> metadata) {
    this.metadata = metadata;
  }

  public SessionServiceCreateSessionRequest1 challenges(@javax.annotation.Nullable SessionServiceRequestChallenges challenges) {
    
    this.challenges = challenges;
    return this;
  }

  /**
   * Get challenges
   * @return challenges
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHALLENGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SessionServiceRequestChallenges getChallenges() {
    return challenges;
  }


  @JsonProperty(JSON_PROPERTY_CHALLENGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChallenges(@javax.annotation.Nullable SessionServiceRequestChallenges challenges) {
    this.challenges = challenges;
  }

  public SessionServiceCreateSessionRequest1 userAgent(@javax.annotation.Nullable SessionServiceUserAgent userAgent) {
    
    this.userAgent = userAgent;
    return this;
  }

  /**
   * Get userAgent
   * @return userAgent
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_AGENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SessionServiceUserAgent getUserAgent() {
    return userAgent;
  }


  @JsonProperty(JSON_PROPERTY_USER_AGENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserAgent(@javax.annotation.Nullable SessionServiceUserAgent userAgent) {
    this.userAgent = userAgent;
  }

  public SessionServiceCreateSessionRequest1 lifetime(@javax.annotation.Nullable String lifetime) {
    
    this.lifetime = lifetime;
    return this;
  }

  /**
   * \&quot;duration (in seconds) after which the session will be automatically invalidated\&quot;
   * @return lifetime
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LIFETIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLifetime() {
    return lifetime;
  }


  @JsonProperty(JSON_PROPERTY_LIFETIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLifetime(@javax.annotation.Nullable String lifetime) {
    this.lifetime = lifetime;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionServiceCreateSessionRequest1 sessionServiceCreateSessionRequest1 = (SessionServiceCreateSessionRequest1) o;
    return Objects.equals(this.checks, sessionServiceCreateSessionRequest1.checks) &&
        Objects.equals(this.metadata, sessionServiceCreateSessionRequest1.metadata) &&
        Objects.equals(this.challenges, sessionServiceCreateSessionRequest1.challenges) &&
        Objects.equals(this.userAgent, sessionServiceCreateSessionRequest1.userAgent) &&
        Objects.equals(this.lifetime, sessionServiceCreateSessionRequest1.lifetime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(checks, metadata, challenges, userAgent, lifetime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionServiceCreateSessionRequest1 {\n");
    sb.append("    checks: ").append(toIndentedString(checks)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    challenges: ").append(toIndentedString(challenges)).append("\n");
    sb.append("    userAgent: ").append(toIndentedString(userAgent)).append("\n");
    sb.append("    lifetime: ").append(toIndentedString(lifetime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `checks` to the URL query string
    if (getChecks() != null) {
      joiner.add(getChecks().toUrlQueryString(prefix + "checks" + suffix));
    }

    // add `metadata` to the URL query string
    if (getMetadata() != null) {
      for (String _key : getMetadata().keySet()) {
        try {
          joiner.add(String.format("%smetadata%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
              getMetadata().get(_key), URLEncoder.encode(String.valueOf(getMetadata().get(_key)), "UTF-8").replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    // add `challenges` to the URL query string
    if (getChallenges() != null) {
      joiner.add(getChallenges().toUrlQueryString(prefix + "challenges" + suffix));
    }

    // add `userAgent` to the URL query string
    if (getUserAgent() != null) {
      joiner.add(getUserAgent().toUrlQueryString(prefix + "userAgent" + suffix));
    }

    // add `lifetime` to the URL query string
    if (getLifetime() != null) {
      try {
        joiner.add(String.format("%slifetime%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLifetime()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

