/*
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zitadel.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zitadel.model.BetaUserServiceStateQuery;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * StateQuery2
 */
@JsonPropertyOrder({
  StateQuery2.JSON_PROPERTY_STATE_QUERY
})
@JsonTypeName("state_query_2")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class StateQuery2 {
  public static final String JSON_PROPERTY_STATE_QUERY = "stateQuery";
  @javax.annotation.Nonnull
  private BetaUserServiceStateQuery stateQuery;

  public StateQuery2() {
  }

  public StateQuery2 stateQuery(@javax.annotation.Nonnull BetaUserServiceStateQuery stateQuery) {
    
    this.stateQuery = stateQuery;
    return this;
  }

  /**
   * Get stateQuery
   * @return stateQuery
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATE_QUERY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BetaUserServiceStateQuery getStateQuery() {
    return stateQuery;
  }


  @JsonProperty(JSON_PROPERTY_STATE_QUERY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStateQuery(@javax.annotation.Nonnull BetaUserServiceStateQuery stateQuery) {
    this.stateQuery = stateQuery;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StateQuery2 stateQuery2 = (StateQuery2) o;
    return Objects.equals(this.stateQuery, stateQuery2.stateQuery);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stateQuery);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StateQuery2 {\n");
    sb.append("    stateQuery: ").append(toIndentedString(stateQuery)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `stateQuery` to the URL query string
    if (getStateQuery() != null) {
      joiner.add(getStateQuery().toUrlQueryString(prefix + "stateQuery" + suffix));
    }

    return joiner.toString();
  }

}

