/*
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zitadel.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zitadel.model.UserServiceAndQuery;
import com.zitadel.model.UserServiceDisplayNameQuery;
import com.zitadel.model.UserServiceEmailQuery;
import com.zitadel.model.UserServiceFirstNameQuery;
import com.zitadel.model.UserServiceInUserEmailsQuery;
import com.zitadel.model.UserServiceInUserIDQuery;
import com.zitadel.model.UserServiceLastNameQuery;
import com.zitadel.model.UserServiceLoginNameQuery;
import com.zitadel.model.UserServiceNickNameQuery;
import com.zitadel.model.UserServiceNotQuery;
import com.zitadel.model.UserServiceOrQuery;
import com.zitadel.model.UserServiceOrganizationIdQuery;
import com.zitadel.model.UserServicePhoneQuery;
import com.zitadel.model.UserServiceStateQuery;
import com.zitadel.model.UserServiceTypeQuery;
import com.zitadel.model.UserServiceUserNameQuery;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * UserServiceSearchQuery
 */
@JsonPropertyOrder({
  UserServiceSearchQuery.JSON_PROPERTY_USER_NAME_QUERY,
  UserServiceSearchQuery.JSON_PROPERTY_FIRST_NAME_QUERY,
  UserServiceSearchQuery.JSON_PROPERTY_LAST_NAME_QUERY,
  UserServiceSearchQuery.JSON_PROPERTY_NICK_NAME_QUERY,
  UserServiceSearchQuery.JSON_PROPERTY_DISPLAY_NAME_QUERY,
  UserServiceSearchQuery.JSON_PROPERTY_EMAIL_QUERY,
  UserServiceSearchQuery.JSON_PROPERTY_STATE_QUERY,
  UserServiceSearchQuery.JSON_PROPERTY_TYPE_QUERY,
  UserServiceSearchQuery.JSON_PROPERTY_LOGIN_NAME_QUERY,
  UserServiceSearchQuery.JSON_PROPERTY_IN_USER_IDS_QUERY,
  UserServiceSearchQuery.JSON_PROPERTY_OR_QUERY,
  UserServiceSearchQuery.JSON_PROPERTY_AND_QUERY,
  UserServiceSearchQuery.JSON_PROPERTY_NOT_QUERY,
  UserServiceSearchQuery.JSON_PROPERTY_IN_USER_EMAILS_QUERY,
  UserServiceSearchQuery.JSON_PROPERTY_ORGANIZATION_ID_QUERY,
  UserServiceSearchQuery.JSON_PROPERTY_PHONE_QUERY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class UserServiceSearchQuery {
  public static final String JSON_PROPERTY_USER_NAME_QUERY = "userNameQuery";
  @javax.annotation.Nullable
  private UserServiceUserNameQuery userNameQuery;

  public static final String JSON_PROPERTY_FIRST_NAME_QUERY = "firstNameQuery";
  @javax.annotation.Nullable
  private UserServiceFirstNameQuery firstNameQuery;

  public static final String JSON_PROPERTY_LAST_NAME_QUERY = "lastNameQuery";
  @javax.annotation.Nullable
  private UserServiceLastNameQuery lastNameQuery;

  public static final String JSON_PROPERTY_NICK_NAME_QUERY = "nickNameQuery";
  @javax.annotation.Nullable
  private UserServiceNickNameQuery nickNameQuery;

  public static final String JSON_PROPERTY_DISPLAY_NAME_QUERY = "displayNameQuery";
  @javax.annotation.Nullable
  private UserServiceDisplayNameQuery displayNameQuery;

  public static final String JSON_PROPERTY_EMAIL_QUERY = "emailQuery";
  @javax.annotation.Nullable
  private UserServiceEmailQuery emailQuery;

  public static final String JSON_PROPERTY_STATE_QUERY = "stateQuery";
  @javax.annotation.Nullable
  private UserServiceStateQuery stateQuery;

  public static final String JSON_PROPERTY_TYPE_QUERY = "typeQuery";
  @javax.annotation.Nullable
  private UserServiceTypeQuery typeQuery;

  public static final String JSON_PROPERTY_LOGIN_NAME_QUERY = "loginNameQuery";
  @javax.annotation.Nullable
  private UserServiceLoginNameQuery loginNameQuery;

  public static final String JSON_PROPERTY_IN_USER_IDS_QUERY = "inUserIdsQuery";
  @javax.annotation.Nullable
  private UserServiceInUserIDQuery inUserIdsQuery;

  public static final String JSON_PROPERTY_OR_QUERY = "orQuery";
  @javax.annotation.Nullable
  private UserServiceOrQuery orQuery;

  public static final String JSON_PROPERTY_AND_QUERY = "andQuery";
  @javax.annotation.Nullable
  private UserServiceAndQuery andQuery;

  public static final String JSON_PROPERTY_NOT_QUERY = "notQuery";
  @javax.annotation.Nullable
  private UserServiceNotQuery notQuery;

  public static final String JSON_PROPERTY_IN_USER_EMAILS_QUERY = "inUserEmailsQuery";
  @javax.annotation.Nullable
  private UserServiceInUserEmailsQuery inUserEmailsQuery;

  public static final String JSON_PROPERTY_ORGANIZATION_ID_QUERY = "organizationIdQuery";
  @javax.annotation.Nullable
  private UserServiceOrganizationIdQuery organizationIdQuery;

  public static final String JSON_PROPERTY_PHONE_QUERY = "phoneQuery";
  @javax.annotation.Nullable
  private UserServicePhoneQuery phoneQuery;

  public UserServiceSearchQuery() {
  }

  public UserServiceSearchQuery userNameQuery(@javax.annotation.Nullable UserServiceUserNameQuery userNameQuery) {
    
    this.userNameQuery = userNameQuery;
    return this;
  }

  /**
   * Get userNameQuery
   * @return userNameQuery
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_NAME_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UserServiceUserNameQuery getUserNameQuery() {
    return userNameQuery;
  }


  @JsonProperty(JSON_PROPERTY_USER_NAME_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserNameQuery(@javax.annotation.Nullable UserServiceUserNameQuery userNameQuery) {
    this.userNameQuery = userNameQuery;
  }

  public UserServiceSearchQuery firstNameQuery(@javax.annotation.Nullable UserServiceFirstNameQuery firstNameQuery) {
    
    this.firstNameQuery = firstNameQuery;
    return this;
  }

  /**
   * Get firstNameQuery
   * @return firstNameQuery
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIRST_NAME_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UserServiceFirstNameQuery getFirstNameQuery() {
    return firstNameQuery;
  }


  @JsonProperty(JSON_PROPERTY_FIRST_NAME_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirstNameQuery(@javax.annotation.Nullable UserServiceFirstNameQuery firstNameQuery) {
    this.firstNameQuery = firstNameQuery;
  }

  public UserServiceSearchQuery lastNameQuery(@javax.annotation.Nullable UserServiceLastNameQuery lastNameQuery) {
    
    this.lastNameQuery = lastNameQuery;
    return this;
  }

  /**
   * Get lastNameQuery
   * @return lastNameQuery
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_NAME_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UserServiceLastNameQuery getLastNameQuery() {
    return lastNameQuery;
  }


  @JsonProperty(JSON_PROPERTY_LAST_NAME_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastNameQuery(@javax.annotation.Nullable UserServiceLastNameQuery lastNameQuery) {
    this.lastNameQuery = lastNameQuery;
  }

  public UserServiceSearchQuery nickNameQuery(@javax.annotation.Nullable UserServiceNickNameQuery nickNameQuery) {
    
    this.nickNameQuery = nickNameQuery;
    return this;
  }

  /**
   * Get nickNameQuery
   * @return nickNameQuery
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NICK_NAME_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UserServiceNickNameQuery getNickNameQuery() {
    return nickNameQuery;
  }


  @JsonProperty(JSON_PROPERTY_NICK_NAME_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNickNameQuery(@javax.annotation.Nullable UserServiceNickNameQuery nickNameQuery) {
    this.nickNameQuery = nickNameQuery;
  }

  public UserServiceSearchQuery displayNameQuery(@javax.annotation.Nullable UserServiceDisplayNameQuery displayNameQuery) {
    
    this.displayNameQuery = displayNameQuery;
    return this;
  }

  /**
   * Get displayNameQuery
   * @return displayNameQuery
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UserServiceDisplayNameQuery getDisplayNameQuery() {
    return displayNameQuery;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayNameQuery(@javax.annotation.Nullable UserServiceDisplayNameQuery displayNameQuery) {
    this.displayNameQuery = displayNameQuery;
  }

  public UserServiceSearchQuery emailQuery(@javax.annotation.Nullable UserServiceEmailQuery emailQuery) {
    
    this.emailQuery = emailQuery;
    return this;
  }

  /**
   * Get emailQuery
   * @return emailQuery
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMAIL_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UserServiceEmailQuery getEmailQuery() {
    return emailQuery;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmailQuery(@javax.annotation.Nullable UserServiceEmailQuery emailQuery) {
    this.emailQuery = emailQuery;
  }

  public UserServiceSearchQuery stateQuery(@javax.annotation.Nullable UserServiceStateQuery stateQuery) {
    
    this.stateQuery = stateQuery;
    return this;
  }

  /**
   * Get stateQuery
   * @return stateQuery
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATE_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UserServiceStateQuery getStateQuery() {
    return stateQuery;
  }


  @JsonProperty(JSON_PROPERTY_STATE_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStateQuery(@javax.annotation.Nullable UserServiceStateQuery stateQuery) {
    this.stateQuery = stateQuery;
  }

  public UserServiceSearchQuery typeQuery(@javax.annotation.Nullable UserServiceTypeQuery typeQuery) {
    
    this.typeQuery = typeQuery;
    return this;
  }

  /**
   * Get typeQuery
   * @return typeQuery
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UserServiceTypeQuery getTypeQuery() {
    return typeQuery;
  }


  @JsonProperty(JSON_PROPERTY_TYPE_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTypeQuery(@javax.annotation.Nullable UserServiceTypeQuery typeQuery) {
    this.typeQuery = typeQuery;
  }

  public UserServiceSearchQuery loginNameQuery(@javax.annotation.Nullable UserServiceLoginNameQuery loginNameQuery) {
    
    this.loginNameQuery = loginNameQuery;
    return this;
  }

  /**
   * Get loginNameQuery
   * @return loginNameQuery
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOGIN_NAME_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UserServiceLoginNameQuery getLoginNameQuery() {
    return loginNameQuery;
  }


  @JsonProperty(JSON_PROPERTY_LOGIN_NAME_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoginNameQuery(@javax.annotation.Nullable UserServiceLoginNameQuery loginNameQuery) {
    this.loginNameQuery = loginNameQuery;
  }

  public UserServiceSearchQuery inUserIdsQuery(@javax.annotation.Nullable UserServiceInUserIDQuery inUserIdsQuery) {
    
    this.inUserIdsQuery = inUserIdsQuery;
    return this;
  }

  /**
   * Get inUserIdsQuery
   * @return inUserIdsQuery
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IN_USER_IDS_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UserServiceInUserIDQuery getInUserIdsQuery() {
    return inUserIdsQuery;
  }


  @JsonProperty(JSON_PROPERTY_IN_USER_IDS_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInUserIdsQuery(@javax.annotation.Nullable UserServiceInUserIDQuery inUserIdsQuery) {
    this.inUserIdsQuery = inUserIdsQuery;
  }

  public UserServiceSearchQuery orQuery(@javax.annotation.Nullable UserServiceOrQuery orQuery) {
    
    this.orQuery = orQuery;
    return this;
  }

  /**
   * Get orQuery
   * @return orQuery
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OR_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UserServiceOrQuery getOrQuery() {
    return orQuery;
  }


  @JsonProperty(JSON_PROPERTY_OR_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrQuery(@javax.annotation.Nullable UserServiceOrQuery orQuery) {
    this.orQuery = orQuery;
  }

  public UserServiceSearchQuery andQuery(@javax.annotation.Nullable UserServiceAndQuery andQuery) {
    
    this.andQuery = andQuery;
    return this;
  }

  /**
   * Get andQuery
   * @return andQuery
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AND_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UserServiceAndQuery getAndQuery() {
    return andQuery;
  }


  @JsonProperty(JSON_PROPERTY_AND_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAndQuery(@javax.annotation.Nullable UserServiceAndQuery andQuery) {
    this.andQuery = andQuery;
  }

  public UserServiceSearchQuery notQuery(@javax.annotation.Nullable UserServiceNotQuery notQuery) {
    
    this.notQuery = notQuery;
    return this;
  }

  /**
   * Get notQuery
   * @return notQuery
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NOT_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UserServiceNotQuery getNotQuery() {
    return notQuery;
  }


  @JsonProperty(JSON_PROPERTY_NOT_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNotQuery(@javax.annotation.Nullable UserServiceNotQuery notQuery) {
    this.notQuery = notQuery;
  }

  public UserServiceSearchQuery inUserEmailsQuery(@javax.annotation.Nullable UserServiceInUserEmailsQuery inUserEmailsQuery) {
    
    this.inUserEmailsQuery = inUserEmailsQuery;
    return this;
  }

  /**
   * Get inUserEmailsQuery
   * @return inUserEmailsQuery
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IN_USER_EMAILS_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UserServiceInUserEmailsQuery getInUserEmailsQuery() {
    return inUserEmailsQuery;
  }


  @JsonProperty(JSON_PROPERTY_IN_USER_EMAILS_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInUserEmailsQuery(@javax.annotation.Nullable UserServiceInUserEmailsQuery inUserEmailsQuery) {
    this.inUserEmailsQuery = inUserEmailsQuery;
  }

  public UserServiceSearchQuery organizationIdQuery(@javax.annotation.Nullable UserServiceOrganizationIdQuery organizationIdQuery) {
    
    this.organizationIdQuery = organizationIdQuery;
    return this;
  }

  /**
   * Get organizationIdQuery
   * @return organizationIdQuery
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORGANIZATION_ID_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UserServiceOrganizationIdQuery getOrganizationIdQuery() {
    return organizationIdQuery;
  }


  @JsonProperty(JSON_PROPERTY_ORGANIZATION_ID_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrganizationIdQuery(@javax.annotation.Nullable UserServiceOrganizationIdQuery organizationIdQuery) {
    this.organizationIdQuery = organizationIdQuery;
  }

  public UserServiceSearchQuery phoneQuery(@javax.annotation.Nullable UserServicePhoneQuery phoneQuery) {
    
    this.phoneQuery = phoneQuery;
    return this;
  }

  /**
   * Get phoneQuery
   * @return phoneQuery
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PHONE_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UserServicePhoneQuery getPhoneQuery() {
    return phoneQuery;
  }


  @JsonProperty(JSON_PROPERTY_PHONE_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhoneQuery(@javax.annotation.Nullable UserServicePhoneQuery phoneQuery) {
    this.phoneQuery = phoneQuery;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserServiceSearchQuery userServiceSearchQuery = (UserServiceSearchQuery) o;
    return Objects.equals(this.userNameQuery, userServiceSearchQuery.userNameQuery) &&
        Objects.equals(this.firstNameQuery, userServiceSearchQuery.firstNameQuery) &&
        Objects.equals(this.lastNameQuery, userServiceSearchQuery.lastNameQuery) &&
        Objects.equals(this.nickNameQuery, userServiceSearchQuery.nickNameQuery) &&
        Objects.equals(this.displayNameQuery, userServiceSearchQuery.displayNameQuery) &&
        Objects.equals(this.emailQuery, userServiceSearchQuery.emailQuery) &&
        Objects.equals(this.stateQuery, userServiceSearchQuery.stateQuery) &&
        Objects.equals(this.typeQuery, userServiceSearchQuery.typeQuery) &&
        Objects.equals(this.loginNameQuery, userServiceSearchQuery.loginNameQuery) &&
        Objects.equals(this.inUserIdsQuery, userServiceSearchQuery.inUserIdsQuery) &&
        Objects.equals(this.orQuery, userServiceSearchQuery.orQuery) &&
        Objects.equals(this.andQuery, userServiceSearchQuery.andQuery) &&
        Objects.equals(this.notQuery, userServiceSearchQuery.notQuery) &&
        Objects.equals(this.inUserEmailsQuery, userServiceSearchQuery.inUserEmailsQuery) &&
        Objects.equals(this.organizationIdQuery, userServiceSearchQuery.organizationIdQuery) &&
        Objects.equals(this.phoneQuery, userServiceSearchQuery.phoneQuery);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userNameQuery, firstNameQuery, lastNameQuery, nickNameQuery, displayNameQuery, emailQuery, stateQuery, typeQuery, loginNameQuery, inUserIdsQuery, orQuery, andQuery, notQuery, inUserEmailsQuery, organizationIdQuery, phoneQuery);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserServiceSearchQuery {\n");
    sb.append("    userNameQuery: ").append(toIndentedString(userNameQuery)).append("\n");
    sb.append("    firstNameQuery: ").append(toIndentedString(firstNameQuery)).append("\n");
    sb.append("    lastNameQuery: ").append(toIndentedString(lastNameQuery)).append("\n");
    sb.append("    nickNameQuery: ").append(toIndentedString(nickNameQuery)).append("\n");
    sb.append("    displayNameQuery: ").append(toIndentedString(displayNameQuery)).append("\n");
    sb.append("    emailQuery: ").append(toIndentedString(emailQuery)).append("\n");
    sb.append("    stateQuery: ").append(toIndentedString(stateQuery)).append("\n");
    sb.append("    typeQuery: ").append(toIndentedString(typeQuery)).append("\n");
    sb.append("    loginNameQuery: ").append(toIndentedString(loginNameQuery)).append("\n");
    sb.append("    inUserIdsQuery: ").append(toIndentedString(inUserIdsQuery)).append("\n");
    sb.append("    orQuery: ").append(toIndentedString(orQuery)).append("\n");
    sb.append("    andQuery: ").append(toIndentedString(andQuery)).append("\n");
    sb.append("    notQuery: ").append(toIndentedString(notQuery)).append("\n");
    sb.append("    inUserEmailsQuery: ").append(toIndentedString(inUserEmailsQuery)).append("\n");
    sb.append("    organizationIdQuery: ").append(toIndentedString(organizationIdQuery)).append("\n");
    sb.append("    phoneQuery: ").append(toIndentedString(phoneQuery)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    return joiner.toString();
  }

}

