/*
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zitadel.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zitadel.model.UserServiceSendPasswordResetLink;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * UserServicePasswordResetRequest
 */
@JsonPropertyOrder({
  UserServicePasswordResetRequest.JSON_PROPERTY_SEND_LINK,
  UserServicePasswordResetRequest.JSON_PROPERTY_RETURN_CODE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class UserServicePasswordResetRequest {
  public static final String JSON_PROPERTY_SEND_LINK = "sendLink";
  @javax.annotation.Nullable
  private UserServiceSendPasswordResetLink sendLink;

  public static final String JSON_PROPERTY_RETURN_CODE = "returnCode";
  @javax.annotation.Nullable
  private Object returnCode;

  public UserServicePasswordResetRequest() {
  }

  public UserServicePasswordResetRequest sendLink(@javax.annotation.Nullable UserServiceSendPasswordResetLink sendLink) {
    
    this.sendLink = sendLink;
    return this;
  }

  /**
   * Get sendLink
   * @return sendLink
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEND_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UserServiceSendPasswordResetLink getSendLink() {
    return sendLink;
  }


  @JsonProperty(JSON_PROPERTY_SEND_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSendLink(@javax.annotation.Nullable UserServiceSendPasswordResetLink sendLink) {
    this.sendLink = sendLink;
  }

  public UserServicePasswordResetRequest returnCode(@javax.annotation.Nullable Object returnCode) {
    
    this.returnCode = returnCode;
    return this;
  }

  /**
   * Get returnCode
   * @return returnCode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RETURN_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getReturnCode() {
    return returnCode;
  }


  @JsonProperty(JSON_PROPERTY_RETURN_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReturnCode(@javax.annotation.Nullable Object returnCode) {
    this.returnCode = returnCode;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserServicePasswordResetRequest userServicePasswordResetRequest = (UserServicePasswordResetRequest) o;
    return Objects.equals(this.sendLink, userServicePasswordResetRequest.sendLink) &&
        Objects.equals(this.returnCode, userServicePasswordResetRequest.returnCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sendLink, returnCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserServicePasswordResetRequest {\n");
    sb.append("    sendLink: ").append(toIndentedString(sendLink)).append("\n");
    sb.append("    returnCode: ").append(toIndentedString(returnCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `sendLink` to the URL query string
    if (getSendLink() != null) {
      joiner.add(getSendLink().toUrlQueryString(prefix + "sendLink" + suffix));
    }

    // add `returnCode` to the URL query string
    if (getReturnCode() != null) {
      try {
        joiner.add(String.format("%sreturnCode%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getReturnCode()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

