// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating
// with your Zitadel environment. This SDK enables you to handle resources, settings, and
// configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

package com.zitadel.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.Nullable;

/** UserServiceListUserMetadataRequest. */
@SuppressWarnings({
  "checkstyle:SummaryJavadoc",
  "checkstyle:JavadocParagraph",
  "checkstyle:SingleLineJavadoc",
  "checkstyle:RequireEmptyLineBeforeBlockTagGroup",
  "checkstyle:NonEmptyAtclauseDescription",
  "checkstyle:JavadocTagContinuationIndentation",
  "checkstyle:AtclauseOrder",
  "checkstyle:InvalidJavadocPosition",
  "checkstyle:AbbreviationAsWordInName",
  "checkstyle:MemberName",
  "checkstyle:OverloadMethodsDeclarationOrder",
  "checkstyle:VariableDeclarationUsageDistance",
  "checkstyle:ConstructorsDeclarationGrouping"
})
public class UserServiceListUserMetadataRequest {

  /**
   * ID of the user under which the metadata is to be listed.
   *
   * <p>Example: {@code null}
   */
  @JsonProperty("userId")
  @Nullable
  public String userId;

  /** Example: {@code null} */
  @JsonProperty("pagination")
  @Nullable
  public UserServicePaginationRequest pagination;

  /**
   * Define the criteria to query for.
   *
   * <p>Example: {@code null}
   */
  @JsonProperty("filters")
  @Nullable
  public List<UserServiceMetadataSearchFilter> filters = new ArrayList<>();

  /** Creates an empty instance. */
  public UserServiceListUserMetadataRequest() {}

  /* Value-equality based on all declared fields. Generated so model
   * instances work correctly as Set/Map keys and in test assertions.
   * Uses pattern-matching `instanceof other` (Java 16+) — required by
   * Error Prone's PatternMatchingInstanceof rule and avoids the
   * EqualsGetClass warning that plain getClass() comparison triggers. */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof UserServiceListUserMetadataRequest other)) {
      return false;
    }
    return java.util.Objects.equals(this.userId, other.userId)
        && java.util.Objects.equals(this.pagination, other.pagination)
        && java.util.Objects.equals(this.filters, other.filters);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(userId, pagination, filters);
  }
}
