// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating
// with your Zitadel environment. This SDK enables you to handle resources, settings, and
// configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

package com.zitadel.model;

/** UserServiceAuthenticationMethodType. */
@SuppressWarnings({
  "checkstyle:SummaryJavadoc",
  "checkstyle:JavadocParagraph",
  "checkstyle:SingleLineJavadoc",
  "checkstyle:RequireEmptyLineBeforeBlockTagGroup",
  "checkstyle:NonEmptyAtclauseDescription",
  "checkstyle:JavadocTagContinuationIndentation",
  "checkstyle:AtclauseOrder",
  "checkstyle:InvalidJavadocPosition",
  "checkstyle:AbbreviationAsWordInName",
  "checkstyle:MemberName",
  "checkstyle:OverloadMethodsDeclarationOrder",
  "checkstyle:VariableDeclarationUsageDistance",
  "checkstyle:ConstructorsDeclarationGrouping"
})
public enum UserServiceAuthenticationMethodType {
  /** The {@code "AUTHENTICATION_METHOD_TYPE_UNSPECIFIED"} value. */
  AUTHENTICATION_METHOD_TYPE_UNSPECIFIED("AUTHENTICATION_METHOD_TYPE_UNSPECIFIED"),
  /** The {@code "AUTHENTICATION_METHOD_TYPE_PASSWORD"} value. */
  AUTHENTICATION_METHOD_TYPE_PASSWORD("AUTHENTICATION_METHOD_TYPE_PASSWORD"),
  /** The {@code "AUTHENTICATION_METHOD_TYPE_PASSKEY"} value. */
  AUTHENTICATION_METHOD_TYPE_PASSKEY("AUTHENTICATION_METHOD_TYPE_PASSKEY"),
  /** The {@code "AUTHENTICATION_METHOD_TYPE_IDP"} value. */
  AUTHENTICATION_METHOD_TYPE_IDP("AUTHENTICATION_METHOD_TYPE_IDP"),
  /** The {@code "AUTHENTICATION_METHOD_TYPE_TOTP"} value. */
  AUTHENTICATION_METHOD_TYPE_TOTP("AUTHENTICATION_METHOD_TYPE_TOTP"),
  /** The {@code "AUTHENTICATION_METHOD_TYPE_U2F"} value. */
  AUTHENTICATION_METHOD_TYPE_U2_F("AUTHENTICATION_METHOD_TYPE_U2F"),
  /** The {@code "AUTHENTICATION_METHOD_TYPE_OTP_SMS"} value. */
  AUTHENTICATION_METHOD_TYPE_OTP_SMS("AUTHENTICATION_METHOD_TYPE_OTP_SMS"),
  /** The {@code "AUTHENTICATION_METHOD_TYPE_OTP_EMAIL"} value. */
  AUTHENTICATION_METHOD_TYPE_OTP_EMAIL("AUTHENTICATION_METHOD_TYPE_OTP_EMAIL"),
  /** The {@code "AUTHENTICATION_METHOD_TYPE_RECOVERY_CODE"} value. */
  AUTHENTICATION_METHOD_TYPE_RECOVERY_CODE("AUTHENTICATION_METHOD_TYPE_RECOVERY_CODE");

  private final String value;

  UserServiceAuthenticationMethodType(String value) {
    this.value = value;
  }

  /**
   * Returns the wire value of this enum constant.
   *
   * @return the wire value
   */
  @com.fasterxml.jackson.annotation.JsonValue
  public String getValue() {
    return value;
  }

  /**
   * Returns the enum constant for the given wire value.
   *
   * @param value the wire value
   * @return the matching enum constant
   * @throws IllegalArgumentException if no constant matches
   */
  @com.fasterxml.jackson.annotation.JsonCreator
  public static UserServiceAuthenticationMethodType fromValue(String value) {
    for (UserServiceAuthenticationMethodType b : values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
