/*
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zitadel.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * V2HumanProfile
 */
@JsonPropertyOrder({
  V2HumanProfile.JSON_PROPERTY_GIVEN_NAME,
  V2HumanProfile.JSON_PROPERTY_FAMILY_NAME,
  V2HumanProfile.JSON_PROPERTY_NICK_NAME,
  V2HumanProfile.JSON_PROPERTY_DISPLAY_NAME,
  V2HumanProfile.JSON_PROPERTY_PREFERRED_LANGUAGE,
  V2HumanProfile.JSON_PROPERTY_GENDER,
  V2HumanProfile.JSON_PROPERTY_AVATAR_URL
})
@JsonTypeName("v2HumanProfile")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class V2HumanProfile {
  public static final String JSON_PROPERTY_GIVEN_NAME = "givenName";
  public static final String JSON_PROPERTY_FAMILY_NAME = "familyName";
  public static final String JSON_PROPERTY_NICK_NAME = "nickName";
  public static final String JSON_PROPERTY_DISPLAY_NAME = "displayName";
  public static final String JSON_PROPERTY_PREFERRED_LANGUAGE = "preferredLanguage";
  public static final String JSON_PROPERTY_GENDER = "gender";
  public static final String JSON_PROPERTY_AVATAR_URL = "avatarUrl";
  @javax.annotation.Nullable
  private String givenName;
  @javax.annotation.Nullable
  private String familyName;
  @javax.annotation.Nullable
  private String nickName;
  @javax.annotation.Nullable
  private String displayName;
  @javax.annotation.Nullable
  private String preferredLanguage;
  @javax.annotation.Nullable
  private V2Gender gender = V2Gender.GENDER_UNSPECIFIED;
  @javax.annotation.Nullable
  private String avatarUrl;

  public V2HumanProfile() {
  }

  public V2HumanProfile givenName(@javax.annotation.Nullable String givenName) {

    this.givenName = givenName;
    return this;
  }

  /**
   * Get givenName
   *
   * @return givenName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GIVEN_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGivenName() {
    return givenName;
  }


  @JsonProperty(JSON_PROPERTY_GIVEN_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGivenName(@javax.annotation.Nullable String givenName) {
    this.givenName = givenName;
  }

  public V2HumanProfile familyName(@javax.annotation.Nullable String familyName) {

    this.familyName = familyName;
    return this;
  }

  /**
   * Get familyName
   *
   * @return familyName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FAMILY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFamilyName() {
    return familyName;
  }


  @JsonProperty(JSON_PROPERTY_FAMILY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFamilyName(@javax.annotation.Nullable String familyName) {
    this.familyName = familyName;
  }

  public V2HumanProfile nickName(@javax.annotation.Nullable String nickName) {

    this.nickName = nickName;
    return this;
  }

  /**
   * Get nickName
   *
   * @return nickName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NICK_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNickName() {
    return nickName;
  }


  @JsonProperty(JSON_PROPERTY_NICK_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNickName(@javax.annotation.Nullable String nickName) {
    this.nickName = nickName;
  }

  public V2HumanProfile displayName(@javax.annotation.Nullable String displayName) {

    this.displayName = displayName;
    return this;
  }

  /**
   * Get displayName
   *
   * @return displayName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDisplayName() {
    return displayName;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayName(@javax.annotation.Nullable String displayName) {
    this.displayName = displayName;
  }

  public V2HumanProfile preferredLanguage(@javax.annotation.Nullable String preferredLanguage) {

    this.preferredLanguage = preferredLanguage;
    return this;
  }

  /**
   * Get preferredLanguage
   *
   * @return preferredLanguage
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PREFERRED_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPreferredLanguage() {
    return preferredLanguage;
  }


  @JsonProperty(JSON_PROPERTY_PREFERRED_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreferredLanguage(@javax.annotation.Nullable String preferredLanguage) {
    this.preferredLanguage = preferredLanguage;
  }

  public V2HumanProfile gender(@javax.annotation.Nullable V2Gender gender) {

    this.gender = gender;
    return this;
  }

  /**
   * Get gender
   *
   * @return gender
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GENDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public V2Gender getGender() {
    return gender;
  }


  @JsonProperty(JSON_PROPERTY_GENDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGender(@javax.annotation.Nullable V2Gender gender) {
    this.gender = gender;
  }

  public V2HumanProfile avatarUrl(@javax.annotation.Nullable String avatarUrl) {

    this.avatarUrl = avatarUrl;
    return this;
  }

  /**
   * avatar URL of the user
   *
   * @return avatarUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AVATAR_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAvatarUrl() {
    return avatarUrl;
  }


  @JsonProperty(JSON_PROPERTY_AVATAR_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvatarUrl(@javax.annotation.Nullable String avatarUrl) {
    this.avatarUrl = avatarUrl;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2HumanProfile v2HumanProfile = (V2HumanProfile) o;
    return Objects.equals(this.givenName, v2HumanProfile.givenName) &&
      Objects.equals(this.familyName, v2HumanProfile.familyName) &&
      Objects.equals(this.nickName, v2HumanProfile.nickName) &&
      Objects.equals(this.displayName, v2HumanProfile.displayName) &&
      Objects.equals(this.preferredLanguage, v2HumanProfile.preferredLanguage) &&
      Objects.equals(this.gender, v2HumanProfile.gender) &&
      Objects.equals(this.avatarUrl, v2HumanProfile.avatarUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(givenName, familyName, nickName, displayName, preferredLanguage, gender, avatarUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2HumanProfile {\n");
    sb.append("    givenName: ").append(toIndentedString(givenName)).append("\n");
    sb.append("    familyName: ").append(toIndentedString(familyName)).append("\n");
    sb.append("    nickName: ").append(toIndentedString(nickName)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    preferredLanguage: ").append(toIndentedString(preferredLanguage)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    avatarUrl: ").append(toIndentedString(avatarUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `givenName` to the URL query string
    if (getGivenName() != null) {
      try {
        joiner.add(String.format("%sgivenName%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getGivenName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `familyName` to the URL query string
    if (getFamilyName() != null) {
      try {
        joiner.add(String.format("%sfamilyName%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFamilyName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `nickName` to the URL query string
    if (getNickName() != null) {
      try {
        joiner.add(String.format("%snickName%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getNickName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `displayName` to the URL query string
    if (getDisplayName() != null) {
      try {
        joiner.add(String.format("%sdisplayName%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDisplayName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `preferredLanguage` to the URL query string
    if (getPreferredLanguage() != null) {
      try {
        joiner.add(String.format("%spreferredLanguage%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPreferredLanguage()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `gender` to the URL query string
    if (getGender() != null) {
      try {
        joiner.add(String.format("%sgender%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getGender()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `avatarUrl` to the URL query string
    if (getAvatarUrl() != null) {
      try {
        joiner.add(String.format("%savatarUrl%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAvatarUrl()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

