/*
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zitadel.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zitadel.model.V2PasskeyAuthenticator;
import com.zitadel.model.V2PasskeyRegistrationCode;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UserServiceRegisterPasskeyBody
 */
class UserServiceRegisterPasskeyBodyTest {
    private final UserServiceRegisterPasskeyBody model = new UserServiceRegisterPasskeyBody();

    /**
     * Model tests for UserServiceRegisterPasskeyBody
     */
    @Test
    void testUserServiceRegisterPasskeyBody() {
        // TODO: test UserServiceRegisterPasskeyBody
    }

    /**
     * Test the property 'code'
     */
    @Test
    void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'authenticator'
     */
    @Test
    void authenticatorTest() {
        // TODO: test authenticator
    }

    /**
     * Test the property 'domain'
     */
    @Test
    void domainTest() {
        // TODO: test domain
    }

}
