/*
 * OpenAI API
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zitadel.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zitadel.model.V2Details;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for V2AddHumanUserResponse
 */
class V2AddHumanUserResponseTest {
    private final V2AddHumanUserResponse model = new V2AddHumanUserResponse();

    /**
     * Model tests for V2AddHumanUserResponse
     */
    @Test
    void testV2AddHumanUserResponse() {
        // TODO: test V2AddHumanUserResponse
    }

    /**
     * Test the property 'userId'
     */
    @Test
    void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'details'
     */
    @Test
    void detailsTest() {
        // TODO: test details
    }

    /**
     * Test the property 'emailCode'
     */
    @Test
    void emailCodeTest() {
        // TODO: test emailCode
    }

    /**
     * Test the property 'phoneCode'
     */
    @Test
    void phoneCodeTest() {
        // TODO: test phoneCode
    }

}
