/*
 * OpenAI API
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zitadel.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for V2GitHubEnterpriseServerConfig
 */
class V2GitHubEnterpriseServerConfigTest {
    private final V2GitHubEnterpriseServerConfig model = new V2GitHubEnterpriseServerConfig();

    /**
     * Model tests for V2GitHubEnterpriseServerConfig
     */
    @Test
    void testV2GitHubEnterpriseServerConfig() {
        // TODO: test V2GitHubEnterpriseServerConfig
    }

    /**
     * Test the property 'clientId'
     */
    @Test
    void clientIdTest() {
        // TODO: test clientId
    }

    /**
     * Test the property 'authorizationEndpoint'
     */
    @Test
    void authorizationEndpointTest() {
        // TODO: test authorizationEndpoint
    }

    /**
     * Test the property 'tokenEndpoint'
     */
    @Test
    void tokenEndpointTest() {
        // TODO: test tokenEndpoint
    }

    /**
     * Test the property 'userEndpoint'
     */
    @Test
    void userEndpointTest() {
        // TODO: test userEndpoint
    }

    /**
     * Test the property 'scopes'
     */
    @Test
    void scopesTest() {
        // TODO: test scopes
    }

}
