/*
 * OpenAI API
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zitadel.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zitadel.model.V2IDPLDAPAccessInformation;
import com.zitadel.model.V2IDPOAuthAccessInformation;
import com.zitadel.model.V2IDPSAMLAccessInformation;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for V2IDPInformation
 */
class V2IDPInformationTest {
    private final V2IDPInformation model = new V2IDPInformation();

    /**
     * Model tests for V2IDPInformation
     */
    @Test
    void testV2IDPInformation() {
        // TODO: test V2IDPInformation
    }

    /**
     * Test the property 'oauth'
     */
    @Test
    void oauthTest() {
        // TODO: test oauth
    }

    /**
     * Test the property 'ldap'
     */
    @Test
    void ldapTest() {
        // TODO: test ldap
    }

    /**
     * Test the property 'saml'
     */
    @Test
    void samlTest() {
        // TODO: test saml
    }

    /**
     * Test the property 'idpId'
     */
    @Test
    void idpIdTest() {
        // TODO: test idpId
    }

    /**
     * Test the property 'userId'
     */
    @Test
    void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'userName'
     */
    @Test
    void userNameTest() {
        // TODO: test userName
    }

    /**
     * Test the property 'rawInformation'
     */
    @Test
    void rawInformationTest() {
        // TODO: test rawInformation
    }

}
