/*
 * OpenAI API
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zitadel.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zitadel.model.V2Details;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for V2ResetUserFeaturesResponse
 */
class V2ResetUserFeaturesResponseTest {
    private final V2ResetUserFeaturesResponse model = new V2ResetUserFeaturesResponse();

    /**
     * Model tests for V2ResetUserFeaturesResponse
     */
    @Test
    void testV2ResetUserFeaturesResponse() {
        // TODO: test V2ResetUserFeaturesResponse
    }

    /**
     * Test the property 'details'
     */
    @Test
    void detailsTest() {
        // TODO: test details
    }

}
