// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating
// with your Zitadel environment. This SDK enables you to handle resources, settings, and
// configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

package com.zitadel.api;

import com.fasterxml.jackson.core.type.TypeReference;
import com.zitadel.ApiClient;
import com.zitadel.ApiException;
import com.zitadel.ApiResult;
import com.zitadel.Configuration;
import com.zitadel.auth.Authenticator;
import com.zitadel.model.BetaOrganizationServiceActivateOrganizationRequest;
import com.zitadel.model.BetaOrganizationServiceActivateOrganizationResponse;
import com.zitadel.model.BetaOrganizationServiceAddOrganizationDomainRequest;
import com.zitadel.model.BetaOrganizationServiceAddOrganizationDomainResponse;
import com.zitadel.model.BetaOrganizationServiceCreateOrganizationRequest;
import com.zitadel.model.BetaOrganizationServiceCreateOrganizationResponse;
import com.zitadel.model.BetaOrganizationServiceDeactivateOrganizationRequest;
import com.zitadel.model.BetaOrganizationServiceDeactivateOrganizationResponse;
import com.zitadel.model.BetaOrganizationServiceDeleteOrganizationDomainRequest;
import com.zitadel.model.BetaOrganizationServiceDeleteOrganizationDomainResponse;
import com.zitadel.model.BetaOrganizationServiceDeleteOrganizationMetadataRequest;
import com.zitadel.model.BetaOrganizationServiceDeleteOrganizationMetadataResponse;
import com.zitadel.model.BetaOrganizationServiceDeleteOrganizationRequest;
import com.zitadel.model.BetaOrganizationServiceDeleteOrganizationResponse;
import com.zitadel.model.BetaOrganizationServiceGenerateOrganizationDomainValidationRequest;
import com.zitadel.model.BetaOrganizationServiceGenerateOrganizationDomainValidationResponse;
import com.zitadel.model.BetaOrganizationServiceListOrganizationDomainsRequest;
import com.zitadel.model.BetaOrganizationServiceListOrganizationDomainsResponse;
import com.zitadel.model.BetaOrganizationServiceListOrganizationMetadataRequest;
import com.zitadel.model.BetaOrganizationServiceListOrganizationMetadataResponse;
import com.zitadel.model.BetaOrganizationServiceListOrganizationsRequest;
import com.zitadel.model.BetaOrganizationServiceListOrganizationsResponse;
import com.zitadel.model.BetaOrganizationServiceSetOrganizationMetadataRequest;
import com.zitadel.model.BetaOrganizationServiceSetOrganizationMetadataResponse;
import com.zitadel.model.BetaOrganizationServiceUpdateOrganizationRequest;
import com.zitadel.model.BetaOrganizationServiceUpdateOrganizationResponse;
import com.zitadel.model.BetaOrganizationServiceVerifyOrganizationDomainRequest;
import com.zitadel.model.BetaOrganizationServiceVerifyOrganizationDomainResponse;
import java.util.HashMap;
import java.util.Map;
import javax.annotation.Nullable;

/** BetaOrganizationServiceApi provides methods for the BetaOrganizationService API group. */
@SuppressWarnings({
  "checkstyle:SummaryJavadoc",
  "checkstyle:JavadocParagraph",
  "checkstyle:SingleLineJavadoc",
  "checkstyle:RequireEmptyLineBeforeBlockTagGroup",
  "checkstyle:NonEmptyAtclauseDescription",
  "checkstyle:JavadocTagContinuationIndentation",
  "checkstyle:AtclauseOrder",
  "checkstyle:InvalidJavadocPosition",
  "checkstyle:AbbreviationAsWordInName",
  "checkstyle:MemberName",
  "checkstyle:OverloadMethodsDeclarationOrder",
  "checkstyle:VariableDeclarationUsageDistance",
  "checkstyle:ConstructorsDeclarationGrouping"
})
public class BetaOrganizationServiceApi extends BaseApi {

  private static final java.lang.reflect.Type activateOrganizationTypeRef =
      new TypeReference<BetaOrganizationServiceActivateOrganizationResponse>() {}.getType();

  private static final java.lang.reflect.Type addOrganizationDomainTypeRef =
      new TypeReference<BetaOrganizationServiceAddOrganizationDomainResponse>() {}.getType();

  private static final java.lang.reflect.Type createOrganizationTypeRef =
      new TypeReference<BetaOrganizationServiceCreateOrganizationResponse>() {}.getType();

  private static final java.lang.reflect.Type deactivateOrganizationTypeRef =
      new TypeReference<BetaOrganizationServiceDeactivateOrganizationResponse>() {}.getType();

  private static final java.lang.reflect.Type deleteOrganizationTypeRef =
      new TypeReference<BetaOrganizationServiceDeleteOrganizationResponse>() {}.getType();

  private static final java.lang.reflect.Type deleteOrganizationDomainTypeRef =
      new TypeReference<BetaOrganizationServiceDeleteOrganizationDomainResponse>() {}.getType();

  private static final java.lang.reflect.Type deleteOrganizationMetadataTypeRef =
      new TypeReference<BetaOrganizationServiceDeleteOrganizationMetadataResponse>() {}.getType();

  private static final java.lang.reflect.Type generateOrganizationDomainValidationTypeRef =
      new TypeReference<
          BetaOrganizationServiceGenerateOrganizationDomainValidationResponse>() {}.getType();

  private static final java.lang.reflect.Type listOrganizationDomainsTypeRef =
      new TypeReference<BetaOrganizationServiceListOrganizationDomainsResponse>() {}.getType();

  private static final java.lang.reflect.Type listOrganizationMetadataTypeRef =
      new TypeReference<BetaOrganizationServiceListOrganizationMetadataResponse>() {}.getType();

  private static final java.lang.reflect.Type listOrganizationsTypeRef =
      new TypeReference<BetaOrganizationServiceListOrganizationsResponse>() {}.getType();

  private static final java.lang.reflect.Type setOrganizationMetadataTypeRef =
      new TypeReference<BetaOrganizationServiceSetOrganizationMetadataResponse>() {}.getType();

  private static final java.lang.reflect.Type updateOrganizationTypeRef =
      new TypeReference<BetaOrganizationServiceUpdateOrganizationResponse>() {}.getType();

  private static final java.lang.reflect.Type verifyOrganizationDomainTypeRef =
      new TypeReference<BetaOrganizationServiceVerifyOrganizationDomainResponse>() {}.getType();

  /** Creates an instance with the default client and configuration. */
  public BetaOrganizationServiceApi() {
    super();
  }

  /**
   * Creates an instance with the given client and configuration.
   *
   * @param apiClient the API client used to execute requests
   * @param config the client configuration
   */
  public BetaOrganizationServiceApi(ApiClient apiClient, Configuration config) {
    super(apiClient, config);
  }

  /**
   * Creates an instance with the given client, configuration, and authenticator.
   *
   * @param apiClient the API client used to execute requests
   * @param config the client configuration
   * @param authenticator the default authenticator, or {@code null} for none
   */
  public BetaOrganizationServiceApi(
      ApiClient apiClient, Configuration config, @Nullable Authenticator authenticator) {
    super(apiClient, config, authenticator);
  }

  /**
   * Activate Organization Deprecated: please move to the corresponding endpoint under organization
   * service v2. This endpoint will be removed with the next major version of ZITADEL. Set the state
   * of my organization to active. The state of the organization has to be deactivated to perform
   * the request. Users of this organization will be able to log in again. Required permission: -
   * `org.write`
   *
   * @param betaOrganizationServiceActivateOrganizationRequest (required)
   * @return {@code BetaOrganizationServiceActivateOrganizationResponse}
   * @throws ApiException if fails to make API call
   */
  public BetaOrganizationServiceActivateOrganizationResponse activateOrganization(
      BetaOrganizationServiceActivateOrganizationRequest
          betaOrganizationServiceActivateOrganizationRequest) {
    return requireBody(
        activateOrganizationWithHttpInfo(betaOrganizationServiceActivateOrganizationRequest),
        "activateOrganization");
  }

  /**
   * Activate Organization Deprecated: please move to the corresponding endpoint under organization
   * service v2. This endpoint will be removed with the next major version of ZITADEL. Set the state
   * of my organization to active. The state of the organization has to be deactivated to perform
   * the request. Users of this organization will be able to log in again. Required permission: -
   * `org.write`
   *
   * @param betaOrganizationServiceActivateOrganizationRequest (required)
   * @return the API result wrapping {@code BetaOrganizationServiceActivateOrganizationResponse}
   * @throws ApiException if fails to make API call
   */
  public ApiResult<BetaOrganizationServiceActivateOrganizationResponse>
      activateOrganizationWithHttpInfo(
          BetaOrganizationServiceActivateOrganizationRequest
              betaOrganizationServiceActivateOrganizationRequest) {
    if (betaOrganizationServiceActivateOrganizationRequest == null) {
      throw new IllegalArgumentException(
          "Missing the required parameter 'betaOrganizationServiceActivateOrganizationRequest' when calling activateOrganization");
    }
    String path = "/zitadel.org.v2beta.OrganizationService/ActivateOrganization";
    Map<String, Object> queryParams = new HashMap<>();
    Map<String, String> headerParams = new HashMap<>();
    return invokeApiForResult(
        "POST",
        path,
        queryParams,
        headerParams,
        betaOrganizationServiceActivateOrganizationRequest,
        new String[] {"application/json"},
        "application/json",
        activateOrganizationTypeRef,
        null);
  }

  /**
   * Add Organization Domain Deprecated: please move to the corresponding endpoint under
   * organization service v2. This endpoint will be removed with the next major version of ZITADEL.
   * Add a new domain to an organization. The domains are used to identify to which organization a
   * user belongs. Required permission: - `org.write`
   *
   * @param betaOrganizationServiceAddOrganizationDomainRequest (required)
   * @return {@code BetaOrganizationServiceAddOrganizationDomainResponse}
   * @throws ApiException if fails to make API call
   */
  public BetaOrganizationServiceAddOrganizationDomainResponse addOrganizationDomain(
      BetaOrganizationServiceAddOrganizationDomainRequest
          betaOrganizationServiceAddOrganizationDomainRequest) {
    return requireBody(
        addOrganizationDomainWithHttpInfo(betaOrganizationServiceAddOrganizationDomainRequest),
        "addOrganizationDomain");
  }

  /**
   * Add Organization Domain Deprecated: please move to the corresponding endpoint under
   * organization service v2. This endpoint will be removed with the next major version of ZITADEL.
   * Add a new domain to an organization. The domains are used to identify to which organization a
   * user belongs. Required permission: - `org.write`
   *
   * @param betaOrganizationServiceAddOrganizationDomainRequest (required)
   * @return the API result wrapping {@code BetaOrganizationServiceAddOrganizationDomainResponse}
   * @throws ApiException if fails to make API call
   */
  public ApiResult<BetaOrganizationServiceAddOrganizationDomainResponse>
      addOrganizationDomainWithHttpInfo(
          BetaOrganizationServiceAddOrganizationDomainRequest
              betaOrganizationServiceAddOrganizationDomainRequest) {
    if (betaOrganizationServiceAddOrganizationDomainRequest == null) {
      throw new IllegalArgumentException(
          "Missing the required parameter 'betaOrganizationServiceAddOrganizationDomainRequest' when calling addOrganizationDomain");
    }
    String path = "/zitadel.org.v2beta.OrganizationService/AddOrganizationDomain";
    Map<String, Object> queryParams = new HashMap<>();
    Map<String, String> headerParams = new HashMap<>();
    return invokeApiForResult(
        "POST",
        path,
        queryParams,
        headerParams,
        betaOrganizationServiceAddOrganizationDomainRequest,
        new String[] {"application/json"},
        "application/json",
        addOrganizationDomainTypeRef,
        null);
  }

  /**
   * Create Organization Create a new organization with an administrative user. If no specific roles
   * are sent for the users, they will be granted the role ORG_OWNER. Required permission: -
   * `org.create` Deprecated: Use
   * [AddOrganization](/apis/resources/org_service_v2/organization-service-add-organization.api.mdx)
   * instead to create an organization.
   *
   * @param betaOrganizationServiceCreateOrganizationRequest (required)
   * @return {@code BetaOrganizationServiceCreateOrganizationResponse}
   * @throws ApiException if fails to make API call
   */
  public BetaOrganizationServiceCreateOrganizationResponse createOrganization(
      BetaOrganizationServiceCreateOrganizationRequest
          betaOrganizationServiceCreateOrganizationRequest) {
    return requireBody(
        createOrganizationWithHttpInfo(betaOrganizationServiceCreateOrganizationRequest),
        "createOrganization");
  }

  /**
   * Create Organization Create a new organization with an administrative user. If no specific roles
   * are sent for the users, they will be granted the role ORG_OWNER. Required permission: -
   * `org.create` Deprecated: Use
   * [AddOrganization](/apis/resources/org_service_v2/organization-service-add-organization.api.mdx)
   * instead to create an organization.
   *
   * @param betaOrganizationServiceCreateOrganizationRequest (required)
   * @return the API result wrapping {@code BetaOrganizationServiceCreateOrganizationResponse}
   * @throws ApiException if fails to make API call
   */
  public ApiResult<BetaOrganizationServiceCreateOrganizationResponse>
      createOrganizationWithHttpInfo(
          BetaOrganizationServiceCreateOrganizationRequest
              betaOrganizationServiceCreateOrganizationRequest) {
    if (betaOrganizationServiceCreateOrganizationRequest == null) {
      throw new IllegalArgumentException(
          "Missing the required parameter 'betaOrganizationServiceCreateOrganizationRequest' when calling createOrganization");
    }
    String path = "/zitadel.org.v2beta.OrganizationService/CreateOrganization";
    Map<String, Object> queryParams = new HashMap<>();
    Map<String, String> headerParams = new HashMap<>();
    return invokeApiForResult(
        "POST",
        path,
        queryParams,
        headerParams,
        betaOrganizationServiceCreateOrganizationRequest,
        new String[] {"application/json"},
        "application/json",
        createOrganizationTypeRef,
        null);
  }

  /**
   * Deactivate Organization Deprecated: please move to the corresponding endpoint under
   * organization service v2. This endpoint will be removed with the next major version of ZITADEL.
   * Sets the state of my organization to deactivated. Users of this organization will not be able
   * to log in. Required permission: - `org.write`
   *
   * @param betaOrganizationServiceDeactivateOrganizationRequest (required)
   * @return {@code BetaOrganizationServiceDeactivateOrganizationResponse}
   * @throws ApiException if fails to make API call
   */
  public BetaOrganizationServiceDeactivateOrganizationResponse deactivateOrganization(
      BetaOrganizationServiceDeactivateOrganizationRequest
          betaOrganizationServiceDeactivateOrganizationRequest) {
    return requireBody(
        deactivateOrganizationWithHttpInfo(betaOrganizationServiceDeactivateOrganizationRequest),
        "deactivateOrganization");
  }

  /**
   * Deactivate Organization Deprecated: please move to the corresponding endpoint under
   * organization service v2. This endpoint will be removed with the next major version of ZITADEL.
   * Sets the state of my organization to deactivated. Users of this organization will not be able
   * to log in. Required permission: - `org.write`
   *
   * @param betaOrganizationServiceDeactivateOrganizationRequest (required)
   * @return the API result wrapping {@code BetaOrganizationServiceDeactivateOrganizationResponse}
   * @throws ApiException if fails to make API call
   */
  public ApiResult<BetaOrganizationServiceDeactivateOrganizationResponse>
      deactivateOrganizationWithHttpInfo(
          BetaOrganizationServiceDeactivateOrganizationRequest
              betaOrganizationServiceDeactivateOrganizationRequest) {
    if (betaOrganizationServiceDeactivateOrganizationRequest == null) {
      throw new IllegalArgumentException(
          "Missing the required parameter 'betaOrganizationServiceDeactivateOrganizationRequest' when calling deactivateOrganization");
    }
    String path = "/zitadel.org.v2beta.OrganizationService/DeactivateOrganization";
    Map<String, Object> queryParams = new HashMap<>();
    Map<String, String> headerParams = new HashMap<>();
    return invokeApiForResult(
        "POST",
        path,
        queryParams,
        headerParams,
        betaOrganizationServiceDeactivateOrganizationRequest,
        new String[] {"application/json"},
        "application/json",
        deactivateOrganizationTypeRef,
        null);
  }

  /**
   * Delete Organization Deprecated: please move to the corresponding endpoint under organization
   * service v2. This endpoint will be removed with the next major version of ZITADEL. Deletes the
   * organization and all its resources (Users, Projects, Grants to and from the org). Users of this
   * organization will not be able to log in. Required permission: - `org.delete`
   *
   * @param betaOrganizationServiceDeleteOrganizationRequest (required)
   * @return {@code BetaOrganizationServiceDeleteOrganizationResponse}
   * @throws ApiException if fails to make API call
   */
  public BetaOrganizationServiceDeleteOrganizationResponse deleteOrganization(
      BetaOrganizationServiceDeleteOrganizationRequest
          betaOrganizationServiceDeleteOrganizationRequest) {
    return requireBody(
        deleteOrganizationWithHttpInfo(betaOrganizationServiceDeleteOrganizationRequest),
        "deleteOrganization");
  }

  /**
   * Delete Organization Deprecated: please move to the corresponding endpoint under organization
   * service v2. This endpoint will be removed with the next major version of ZITADEL. Deletes the
   * organization and all its resources (Users, Projects, Grants to and from the org). Users of this
   * organization will not be able to log in. Required permission: - `org.delete`
   *
   * @param betaOrganizationServiceDeleteOrganizationRequest (required)
   * @return the API result wrapping {@code BetaOrganizationServiceDeleteOrganizationResponse}
   * @throws ApiException if fails to make API call
   */
  public ApiResult<BetaOrganizationServiceDeleteOrganizationResponse>
      deleteOrganizationWithHttpInfo(
          BetaOrganizationServiceDeleteOrganizationRequest
              betaOrganizationServiceDeleteOrganizationRequest) {
    if (betaOrganizationServiceDeleteOrganizationRequest == null) {
      throw new IllegalArgumentException(
          "Missing the required parameter 'betaOrganizationServiceDeleteOrganizationRequest' when calling deleteOrganization");
    }
    String path = "/zitadel.org.v2beta.OrganizationService/DeleteOrganization";
    Map<String, Object> queryParams = new HashMap<>();
    Map<String, String> headerParams = new HashMap<>();
    return invokeApiForResult(
        "POST",
        path,
        queryParams,
        headerParams,
        betaOrganizationServiceDeleteOrganizationRequest,
        new String[] {"application/json"},
        "application/json",
        deleteOrganizationTypeRef,
        null);
  }

  /**
   * Delete Organization Domain Deprecated: please move to the corresponding endpoint under
   * organization service v2. This endpoint will be removed with the next major version of ZITADEL.
   * Delete a new domain from an organization. The domains are used to identify to which
   * organization a user belongs. If the uses use the domain for login, this will not be possible
   * afterwards. They have to use another domain instead. Required permission: - `org.write`
   *
   * @param betaOrganizationServiceDeleteOrganizationDomainRequest (required)
   * @return {@code BetaOrganizationServiceDeleteOrganizationDomainResponse}
   * @throws ApiException if fails to make API call
   */
  public BetaOrganizationServiceDeleteOrganizationDomainResponse deleteOrganizationDomain(
      BetaOrganizationServiceDeleteOrganizationDomainRequest
          betaOrganizationServiceDeleteOrganizationDomainRequest) {
    return requireBody(
        deleteOrganizationDomainWithHttpInfo(
            betaOrganizationServiceDeleteOrganizationDomainRequest),
        "deleteOrganizationDomain");
  }

  /**
   * Delete Organization Domain Deprecated: please move to the corresponding endpoint under
   * organization service v2. This endpoint will be removed with the next major version of ZITADEL.
   * Delete a new domain from an organization. The domains are used to identify to which
   * organization a user belongs. If the uses use the domain for login, this will not be possible
   * afterwards. They have to use another domain instead. Required permission: - `org.write`
   *
   * @param betaOrganizationServiceDeleteOrganizationDomainRequest (required)
   * @return the API result wrapping {@code BetaOrganizationServiceDeleteOrganizationDomainResponse}
   * @throws ApiException if fails to make API call
   */
  public ApiResult<BetaOrganizationServiceDeleteOrganizationDomainResponse>
      deleteOrganizationDomainWithHttpInfo(
          BetaOrganizationServiceDeleteOrganizationDomainRequest
              betaOrganizationServiceDeleteOrganizationDomainRequest) {
    if (betaOrganizationServiceDeleteOrganizationDomainRequest == null) {
      throw new IllegalArgumentException(
          "Missing the required parameter 'betaOrganizationServiceDeleteOrganizationDomainRequest' when calling deleteOrganizationDomain");
    }
    String path = "/zitadel.org.v2beta.OrganizationService/DeleteOrganizationDomain";
    Map<String, Object> queryParams = new HashMap<>();
    Map<String, String> headerParams = new HashMap<>();
    return invokeApiForResult(
        "POST",
        path,
        queryParams,
        headerParams,
        betaOrganizationServiceDeleteOrganizationDomainRequest,
        new String[] {"application/json"},
        "application/json",
        deleteOrganizationDomainTypeRef,
        null);
  }

  /**
   * Delete Organization Metadata Deprecated: please move to the corresponding endpoint under
   * organization service v2. This endpoint will be removed with the next major version of ZITADEL.
   * Delete metadata objects from an organization with a specific key. Required permission: -
   * `org.write`
   *
   * @param betaOrganizationServiceDeleteOrganizationMetadataRequest (required)
   * @return {@code BetaOrganizationServiceDeleteOrganizationMetadataResponse}
   * @throws ApiException if fails to make API call
   */
  public BetaOrganizationServiceDeleteOrganizationMetadataResponse deleteOrganizationMetadata(
      BetaOrganizationServiceDeleteOrganizationMetadataRequest
          betaOrganizationServiceDeleteOrganizationMetadataRequest) {
    return requireBody(
        deleteOrganizationMetadataWithHttpInfo(
            betaOrganizationServiceDeleteOrganizationMetadataRequest),
        "deleteOrganizationMetadata");
  }

  /**
   * Delete Organization Metadata Deprecated: please move to the corresponding endpoint under
   * organization service v2. This endpoint will be removed with the next major version of ZITADEL.
   * Delete metadata objects from an organization with a specific key. Required permission: -
   * `org.write`
   *
   * @param betaOrganizationServiceDeleteOrganizationMetadataRequest (required)
   * @return the API result wrapping {@code
   *     BetaOrganizationServiceDeleteOrganizationMetadataResponse}
   * @throws ApiException if fails to make API call
   */
  public ApiResult<BetaOrganizationServiceDeleteOrganizationMetadataResponse>
      deleteOrganizationMetadataWithHttpInfo(
          BetaOrganizationServiceDeleteOrganizationMetadataRequest
              betaOrganizationServiceDeleteOrganizationMetadataRequest) {
    if (betaOrganizationServiceDeleteOrganizationMetadataRequest == null) {
      throw new IllegalArgumentException(
          "Missing the required parameter 'betaOrganizationServiceDeleteOrganizationMetadataRequest' when calling deleteOrganizationMetadata");
    }
    String path = "/zitadel.org.v2beta.OrganizationService/DeleteOrganizationMetadata";
    Map<String, Object> queryParams = new HashMap<>();
    Map<String, String> headerParams = new HashMap<>();
    return invokeApiForResult(
        "POST",
        path,
        queryParams,
        headerParams,
        betaOrganizationServiceDeleteOrganizationMetadataRequest,
        new String[] {"application/json"},
        "application/json",
        deleteOrganizationMetadataTypeRef,
        null);
  }

  /**
   * Generate Organization Domain Validation Deprecated: please move to the corresponding endpoint
   * under organization service v2. This endpoint will be removed with the next major version of
   * ZITADEL. Generate a new file to be able to verify your domain with DNS or HTTP challenge.
   * Required permission: - `org.write`
   *
   * @param betaOrganizationServiceGenerateOrganizationDomainValidationRequest (required)
   * @return {@code BetaOrganizationServiceGenerateOrganizationDomainValidationResponse}
   * @throws ApiException if fails to make API call
   */
  public BetaOrganizationServiceGenerateOrganizationDomainValidationResponse
      generateOrganizationDomainValidation(
          BetaOrganizationServiceGenerateOrganizationDomainValidationRequest
              betaOrganizationServiceGenerateOrganizationDomainValidationRequest) {
    return requireBody(
        generateOrganizationDomainValidationWithHttpInfo(
            betaOrganizationServiceGenerateOrganizationDomainValidationRequest),
        "generateOrganizationDomainValidation");
  }

  /**
   * Generate Organization Domain Validation Deprecated: please move to the corresponding endpoint
   * under organization service v2. This endpoint will be removed with the next major version of
   * ZITADEL. Generate a new file to be able to verify your domain with DNS or HTTP challenge.
   * Required permission: - `org.write`
   *
   * @param betaOrganizationServiceGenerateOrganizationDomainValidationRequest (required)
   * @return the API result wrapping {@code
   *     BetaOrganizationServiceGenerateOrganizationDomainValidationResponse}
   * @throws ApiException if fails to make API call
   */
  public ApiResult<BetaOrganizationServiceGenerateOrganizationDomainValidationResponse>
      generateOrganizationDomainValidationWithHttpInfo(
          BetaOrganizationServiceGenerateOrganizationDomainValidationRequest
              betaOrganizationServiceGenerateOrganizationDomainValidationRequest) {
    if (betaOrganizationServiceGenerateOrganizationDomainValidationRequest == null) {
      throw new IllegalArgumentException(
          "Missing the required parameter 'betaOrganizationServiceGenerateOrganizationDomainValidationRequest' when calling generateOrganizationDomainValidation");
    }
    String path = "/zitadel.org.v2beta.OrganizationService/GenerateOrganizationDomainValidation";
    Map<String, Object> queryParams = new HashMap<>();
    Map<String, String> headerParams = new HashMap<>();
    return invokeApiForResult(
        "POST",
        path,
        queryParams,
        headerParams,
        betaOrganizationServiceGenerateOrganizationDomainValidationRequest,
        new String[] {"application/json"},
        "application/json",
        generateOrganizationDomainValidationTypeRef,
        null);
  }

  /**
   * List Organization Domains Deprecated: please move to the corresponding endpoint under
   * organization service v2. This endpoint will be removed with the next major version of ZITADEL.
   * Returns the list of registered domains of an organization. The domains are used to identify to
   * which organization a user belongs. Required permission: - `org.read`
   *
   * @param betaOrganizationServiceListOrganizationDomainsRequest (required)
   * @return {@code BetaOrganizationServiceListOrganizationDomainsResponse}
   * @throws ApiException if fails to make API call
   */
  public BetaOrganizationServiceListOrganizationDomainsResponse listOrganizationDomains(
      BetaOrganizationServiceListOrganizationDomainsRequest
          betaOrganizationServiceListOrganizationDomainsRequest) {
    return requireBody(
        listOrganizationDomainsWithHttpInfo(betaOrganizationServiceListOrganizationDomainsRequest),
        "listOrganizationDomains");
  }

  /**
   * List Organization Domains Deprecated: please move to the corresponding endpoint under
   * organization service v2. This endpoint will be removed with the next major version of ZITADEL.
   * Returns the list of registered domains of an organization. The domains are used to identify to
   * which organization a user belongs. Required permission: - `org.read`
   *
   * @param betaOrganizationServiceListOrganizationDomainsRequest (required)
   * @return the API result wrapping {@code BetaOrganizationServiceListOrganizationDomainsResponse}
   * @throws ApiException if fails to make API call
   */
  public ApiResult<BetaOrganizationServiceListOrganizationDomainsResponse>
      listOrganizationDomainsWithHttpInfo(
          BetaOrganizationServiceListOrganizationDomainsRequest
              betaOrganizationServiceListOrganizationDomainsRequest) {
    if (betaOrganizationServiceListOrganizationDomainsRequest == null) {
      throw new IllegalArgumentException(
          "Missing the required parameter 'betaOrganizationServiceListOrganizationDomainsRequest' when calling listOrganizationDomains");
    }
    String path = "/zitadel.org.v2beta.OrganizationService/ListOrganizationDomains";
    Map<String, Object> queryParams = new HashMap<>();
    Map<String, String> headerParams = new HashMap<>();
    return invokeApiForResult(
        "POST",
        path,
        queryParams,
        headerParams,
        betaOrganizationServiceListOrganizationDomainsRequest,
        new String[] {"application/json"},
        "application/json",
        listOrganizationDomainsTypeRef,
        null);
  }

  /**
   * List Organization Metadata Deprecated: please move to the corresponding endpoint under
   * organization service v2. This endpoint will be removed with the next major version of ZITADEL.
   * List metadata of an organization filtered by query. Required permission: - `org.read`
   *
   * @param betaOrganizationServiceListOrganizationMetadataRequest (required)
   * @return {@code BetaOrganizationServiceListOrganizationMetadataResponse}
   * @throws ApiException if fails to make API call
   */
  public BetaOrganizationServiceListOrganizationMetadataResponse listOrganizationMetadata(
      BetaOrganizationServiceListOrganizationMetadataRequest
          betaOrganizationServiceListOrganizationMetadataRequest) {
    return requireBody(
        listOrganizationMetadataWithHttpInfo(
            betaOrganizationServiceListOrganizationMetadataRequest),
        "listOrganizationMetadata");
  }

  /**
   * List Organization Metadata Deprecated: please move to the corresponding endpoint under
   * organization service v2. This endpoint will be removed with the next major version of ZITADEL.
   * List metadata of an organization filtered by query. Required permission: - `org.read`
   *
   * @param betaOrganizationServiceListOrganizationMetadataRequest (required)
   * @return the API result wrapping {@code BetaOrganizationServiceListOrganizationMetadataResponse}
   * @throws ApiException if fails to make API call
   */
  public ApiResult<BetaOrganizationServiceListOrganizationMetadataResponse>
      listOrganizationMetadataWithHttpInfo(
          BetaOrganizationServiceListOrganizationMetadataRequest
              betaOrganizationServiceListOrganizationMetadataRequest) {
    if (betaOrganizationServiceListOrganizationMetadataRequest == null) {
      throw new IllegalArgumentException(
          "Missing the required parameter 'betaOrganizationServiceListOrganizationMetadataRequest' when calling listOrganizationMetadata");
    }
    String path = "/zitadel.org.v2beta.OrganizationService/ListOrganizationMetadata";
    Map<String, Object> queryParams = new HashMap<>();
    Map<String, String> headerParams = new HashMap<>();
    return invokeApiForResult(
        "POST",
        path,
        queryParams,
        headerParams,
        betaOrganizationServiceListOrganizationMetadataRequest,
        new String[] {"application/json"},
        "application/json",
        listOrganizationMetadataTypeRef,
        null);
  }

  /**
   * List Organizations Deprecated: please move to the corresponding endpoint under organization
   * service v2. This endpoint will be removed with the next major version of ZITADEL. Returns a
   * list of organizations that match the requesting filters. All filters are applied with an AND
   * condition. Required permission: - `org.read` Deprecated: Use
   * [ListOrganizations](/apis/resources/org_service_v2/organization-service-list-organizations.api.mdx)
   * instead to list organizations.
   *
   * @param betaOrganizationServiceListOrganizationsRequest (required)
   * @return {@code BetaOrganizationServiceListOrganizationsResponse}
   * @throws ApiException if fails to make API call
   */
  public BetaOrganizationServiceListOrganizationsResponse listOrganizations(
      BetaOrganizationServiceListOrganizationsRequest
          betaOrganizationServiceListOrganizationsRequest) {
    return requireBody(
        listOrganizationsWithHttpInfo(betaOrganizationServiceListOrganizationsRequest),
        "listOrganizations");
  }

  /**
   * List Organizations Deprecated: please move to the corresponding endpoint under organization
   * service v2. This endpoint will be removed with the next major version of ZITADEL. Returns a
   * list of organizations that match the requesting filters. All filters are applied with an AND
   * condition. Required permission: - `org.read` Deprecated: Use
   * [ListOrganizations](/apis/resources/org_service_v2/organization-service-list-organizations.api.mdx)
   * instead to list organizations.
   *
   * @param betaOrganizationServiceListOrganizationsRequest (required)
   * @return the API result wrapping {@code BetaOrganizationServiceListOrganizationsResponse}
   * @throws ApiException if fails to make API call
   */
  public ApiResult<BetaOrganizationServiceListOrganizationsResponse> listOrganizationsWithHttpInfo(
      BetaOrganizationServiceListOrganizationsRequest
          betaOrganizationServiceListOrganizationsRequest) {
    if (betaOrganizationServiceListOrganizationsRequest == null) {
      throw new IllegalArgumentException(
          "Missing the required parameter 'betaOrganizationServiceListOrganizationsRequest' when calling listOrganizations");
    }
    String path = "/zitadel.org.v2beta.OrganizationService/ListOrganizations";
    Map<String, Object> queryParams = new HashMap<>();
    Map<String, String> headerParams = new HashMap<>();
    return invokeApiForResult(
        "POST",
        path,
        queryParams,
        headerParams,
        betaOrganizationServiceListOrganizationsRequest,
        new String[] {"application/json"},
        "application/json",
        listOrganizationsTypeRef,
        null);
  }

  /**
   * Set Organization Metadata Deprecated: please move to the corresponding endpoint under
   * organization service v2. This endpoint will be removed with the next major version of ZITADEL.
   * Adds or updates a metadata value for the requested key. Make sure the value is base64 encoded.
   * Required permission: - `org.write`
   *
   * @param betaOrganizationServiceSetOrganizationMetadataRequest (required)
   * @return {@code BetaOrganizationServiceSetOrganizationMetadataResponse}
   * @throws ApiException if fails to make API call
   */
  public BetaOrganizationServiceSetOrganizationMetadataResponse setOrganizationMetadata(
      BetaOrganizationServiceSetOrganizationMetadataRequest
          betaOrganizationServiceSetOrganizationMetadataRequest) {
    return requireBody(
        setOrganizationMetadataWithHttpInfo(betaOrganizationServiceSetOrganizationMetadataRequest),
        "setOrganizationMetadata");
  }

  /**
   * Set Organization Metadata Deprecated: please move to the corresponding endpoint under
   * organization service v2. This endpoint will be removed with the next major version of ZITADEL.
   * Adds or updates a metadata value for the requested key. Make sure the value is base64 encoded.
   * Required permission: - `org.write`
   *
   * @param betaOrganizationServiceSetOrganizationMetadataRequest (required)
   * @return the API result wrapping {@code BetaOrganizationServiceSetOrganizationMetadataResponse}
   * @throws ApiException if fails to make API call
   */
  public ApiResult<BetaOrganizationServiceSetOrganizationMetadataResponse>
      setOrganizationMetadataWithHttpInfo(
          BetaOrganizationServiceSetOrganizationMetadataRequest
              betaOrganizationServiceSetOrganizationMetadataRequest) {
    if (betaOrganizationServiceSetOrganizationMetadataRequest == null) {
      throw new IllegalArgumentException(
          "Missing the required parameter 'betaOrganizationServiceSetOrganizationMetadataRequest' when calling setOrganizationMetadata");
    }
    String path = "/zitadel.org.v2beta.OrganizationService/SetOrganizationMetadata";
    Map<String, Object> queryParams = new HashMap<>();
    Map<String, String> headerParams = new HashMap<>();
    return invokeApiForResult(
        "POST",
        path,
        queryParams,
        headerParams,
        betaOrganizationServiceSetOrganizationMetadataRequest,
        new String[] {"application/json"},
        "application/json",
        setOrganizationMetadataTypeRef,
        null);
  }

  /**
   * Update Organization Deprecated: please move to the corresponding endpoint under organization
   * service v2. This endpoint will be removed with the next major version of ZITADEL. Change the
   * name of the organization. Required permission: - `org.write`
   *
   * @param betaOrganizationServiceUpdateOrganizationRequest (required)
   * @return {@code BetaOrganizationServiceUpdateOrganizationResponse}
   * @throws ApiException if fails to make API call
   */
  public BetaOrganizationServiceUpdateOrganizationResponse updateOrganization(
      BetaOrganizationServiceUpdateOrganizationRequest
          betaOrganizationServiceUpdateOrganizationRequest) {
    return requireBody(
        updateOrganizationWithHttpInfo(betaOrganizationServiceUpdateOrganizationRequest),
        "updateOrganization");
  }

  /**
   * Update Organization Deprecated: please move to the corresponding endpoint under organization
   * service v2. This endpoint will be removed with the next major version of ZITADEL. Change the
   * name of the organization. Required permission: - `org.write`
   *
   * @param betaOrganizationServiceUpdateOrganizationRequest (required)
   * @return the API result wrapping {@code BetaOrganizationServiceUpdateOrganizationResponse}
   * @throws ApiException if fails to make API call
   */
  public ApiResult<BetaOrganizationServiceUpdateOrganizationResponse>
      updateOrganizationWithHttpInfo(
          BetaOrganizationServiceUpdateOrganizationRequest
              betaOrganizationServiceUpdateOrganizationRequest) {
    if (betaOrganizationServiceUpdateOrganizationRequest == null) {
      throw new IllegalArgumentException(
          "Missing the required parameter 'betaOrganizationServiceUpdateOrganizationRequest' when calling updateOrganization");
    }
    String path = "/zitadel.org.v2beta.OrganizationService/UpdateOrganization";
    Map<String, Object> queryParams = new HashMap<>();
    Map<String, String> headerParams = new HashMap<>();
    return invokeApiForResult(
        "POST",
        path,
        queryParams,
        headerParams,
        betaOrganizationServiceUpdateOrganizationRequest,
        new String[] {"application/json"},
        "application/json",
        updateOrganizationTypeRef,
        null);
  }

  /**
   * Verify Organization Domain Deprecated: please move to the corresponding endpoint under
   * organization service v2. This endpoint will be removed with the next major version of ZITADEL.
   * Make sure you have added the required verification to your domain, depending on the method you
   * have chosen (HTTP or DNS challenge). ZITADEL will check it and set the domain as verified if it
   * was successful. A verify domain has to be unique. Required permission: - `org.write`
   *
   * @param betaOrganizationServiceVerifyOrganizationDomainRequest (required)
   * @return {@code BetaOrganizationServiceVerifyOrganizationDomainResponse}
   * @throws ApiException if fails to make API call
   */
  public BetaOrganizationServiceVerifyOrganizationDomainResponse verifyOrganizationDomain(
      BetaOrganizationServiceVerifyOrganizationDomainRequest
          betaOrganizationServiceVerifyOrganizationDomainRequest) {
    return requireBody(
        verifyOrganizationDomainWithHttpInfo(
            betaOrganizationServiceVerifyOrganizationDomainRequest),
        "verifyOrganizationDomain");
  }

  /**
   * Verify Organization Domain Deprecated: please move to the corresponding endpoint under
   * organization service v2. This endpoint will be removed with the next major version of ZITADEL.
   * Make sure you have added the required verification to your domain, depending on the method you
   * have chosen (HTTP or DNS challenge). ZITADEL will check it and set the domain as verified if it
   * was successful. A verify domain has to be unique. Required permission: - `org.write`
   *
   * @param betaOrganizationServiceVerifyOrganizationDomainRequest (required)
   * @return the API result wrapping {@code BetaOrganizationServiceVerifyOrganizationDomainResponse}
   * @throws ApiException if fails to make API call
   */
  public ApiResult<BetaOrganizationServiceVerifyOrganizationDomainResponse>
      verifyOrganizationDomainWithHttpInfo(
          BetaOrganizationServiceVerifyOrganizationDomainRequest
              betaOrganizationServiceVerifyOrganizationDomainRequest) {
    if (betaOrganizationServiceVerifyOrganizationDomainRequest == null) {
      throw new IllegalArgumentException(
          "Missing the required parameter 'betaOrganizationServiceVerifyOrganizationDomainRequest' when calling verifyOrganizationDomain");
    }
    String path = "/zitadel.org.v2beta.OrganizationService/VerifyOrganizationDomain";
    Map<String, Object> queryParams = new HashMap<>();
    Map<String, String> headerParams = new HashMap<>();
    return invokeApiForResult(
        "POST",
        path,
        queryParams,
        headerParams,
        betaOrganizationServiceVerifyOrganizationDomainRequest,
        new String[] {"application/json"},
        "application/json",
        verifyOrganizationDomainTypeRef,
        null);
  }

  /**
   * Unwrap the body of a body-returning operation, throwing a typed {@link ApiException} when the
   * server returned no decodable body (for example an empty or 204 response). The plain convenience
   * accessor must never hand back a silent {@code null} for a declared non-void return type —
   * callers get a catchable, typed error instead.
   *
   * @param result the API result whose data should be present
   * @param operation the operation id, for the error message
   * @param <T> the response body type
   * @return the non-null response body
   * @throws ApiException if the result carries no body
   */
  private static <T> T requireBody(ApiResult<T> result, String operation) {
    T data = result.data();
    if (data == null) {
      throw new ApiException(
          result.statusCode(),
          "Operation '"
              + operation
              + "' returned an empty response body for a body-returning operation",
          result.headers(),
          result.rawBody());
    }
    return data;
  }
}
