name: Compatibility

on:
  workflow_call:
    inputs:
      library_ref:
        required: true
        type: string
      sanity_ref:
        required: true
        type: string

permissions:
  contents: read

jobs:
  check-compatibility:
    name: With Java ${{ matrix.java-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ '11', '17', '21' ]
      fail-fast: false

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.library_ref }}
          path: project/library

      - name: Checkout sanity stub
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.sanity_ref }}
          path: project/sanity

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'corretto'
          cache: maven

      - name: Build Library
        working-directory: project/library
        run: mvn clean install -DskipErrorProne=true -Dspotbugs.skip=true --batch-mode -DskipTests

      - name: Check Installability
        working-directory: project/sanity
        run: mvn clean test -DskipErrorProne=true -Dspotbugs.skip=true --batch-mode
