name: Compatibility

on:
  workflow_call:
    inputs:
      library_ref:
        required: true
        type: string
      sanity_ref:
        required: true
        type: string

jobs:
  check-compatibility:
    name: With Java ${{ matrix.java-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ '8', '11', '17', '21' ]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.library_ref }}
          path: project/library

      - name: Checkout sanity stub
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sanity_ref }}
          path: project/sanity

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'corretto'
          cache: maven

      - name: Workaround - Remove incompatible JVM args for Java 8
        if: matrix.java-version == '8'
        working-directory: project/library
        run: |
          echo "Applying Java 8 workaround for .mvn/jvm.config..."
          if [ -f .mvn/jvm.config ]; then
            sed -i '/^--add-exports=/d' .mvn/jvm.config
            echo "Temporarily modified .mvn/jvm.config for Java 8 build (removed --add-exports lines, no backup):"
            cat .mvn/jvm.config
          else
            echo ".mvn/jvm.config not found in project/library, skipping modification."
          fi
        shell: bash

      - name: Build Library
        working-directory: project/library
        run: mvn clean install -DskipErrorProne=true --batch-mode -DskipTests

      - name: Check Installability
        working-directory: project/sanity
        run: mvn clean test -DskipErrorProne=true --batch-mode
